Repository projectcalico/libcalico-go, pull requests merged in 2018-03, with the labels that each got.

#785 Fix IPAM affinity race conditions on allocation and release
  lib/backend/model/block_affinity.go
  lib/ipam/ipam.go
  lib/ipam/ipam_block.go
  lib/ipam/ipam_block_reader_writer.go
  lib/ipam/ipam_block_reader_writer_test.go
  lib/ipam/ipam_errors.go
  lib/ipam/ipam_suite_test.go
  lib/ipam/ipam_test.go
Labels: release-note-required

#806 Fix bug where IPs were assigned from affine blocks of disabled pools.
  lib/ipam/ipam.go
  lib/ipam/ipam_block_reader_writer.go
  lib/ipam/ipam_test.go
Labels: release-note-required

#819 cherry-pick: #785 and #806
  lib/backend/model/block_affinity.go
  lib/ipam/ipam.go
  lib/ipam/ipam_block.go
  lib/ipam/ipam_block_reader_writer.go
  lib/ipam/ipam_block_reader_writer_test.go
  lib/ipam/ipam_errors.go
  lib/ipam/ipam_suite_test.go
  lib/ipam/ipam_test.go
Labels: release-note-required

#822 Fix bad error check on update conflict
  lib/ipam/ipam.go
Labels: cherry-pick-candidate

#821 KDD should return a real BlockAffinity
  lib/backend/k8s/resources/affinityblock.go
  lib/backend/syncersv1/bgpsyncer/bgpsyncer_e2e_test.go
Labels: bugfix, cherry-pick-candidate

#830 Allow . in interface names
  lib/validator/v1/validator.go
  lib/validator/v1/validator_test.go
  lib/validator/v3/validator.go
  lib/validator/v3/validator_test.go
Labels: cherry-pick-candidate

#833 Cherry pick #830 to release-v3.1
  lib/validator/v1/validator.go
  lib/validator/v1/validator_test.go
  lib/validator/v3/validator.go
  lib/validator/v3/validator_test.go
Labels: release-note-required

#832 Cherry pick #830 to release-v3.0
  lib/validator/v1/validator.go
  lib/validator/v1/validator_test.go
  lib/validator/v3/validator.go
  lib/validator/v3/validator_test.go
Labels: release-note-required

#834 Cherry pick #830 to release-v2.6
  lib/validator/validator.go
  lib/validator/validator_test.go
Labels: release-note-required
