Repository projectcalico/libcalico-go, pull requests merged in 2018-05, with the labels that each got.

#865 [release-v3.1] Allow configuration of veth prefix in KDD mode
  lib/backend/k8s/conversion/conversion.go
  lib/backend/k8s/conversion/conversion_test.go
Labels: release-note-required

#864 [release-v3.0] Allow configuration of veth prefix in KDD mode
  lib/backend/k8s/conversion/conversion.go
  lib/backend/k8s/conversion/conversion_test.go
Labels: release-note-required

#867 Support pod and namespace selectors in K8s policy
  lib/backend/k8s/conversion/conversion.go
  lib/backend/k8s/conversion/conversion_test.go
Labels: cherry-pick-candidate, release-note-required

#868 bugfix: IPAM block affinity leaks after upgrade
  lib/backend/model/keys.go
  lib/backend/model/keys_test.go
Labels: bugfix, cherry-pick-candidate, release-note-required

#870 [release-v3.1] cherry pick: bugfix: IPAM block affinity leaks after upgrade
  lib/backend/model/keys.go
  lib/backend/model/keys_test.go
Labels: release-note-required

#871 Support pod and namespace selectors in K8s policy
  lib/backend/k8s/conversion/conversion.go
  lib/backend/k8s/conversion/conversion_test.go
Labels: release-note-required
