Repository projectcalico/libcalico-go, pull requests merged in 2019-11, with the labels that each got.

#1154 Selector field not required
  Makefile
  lib/apis/v3/globalnetworkpolicy.go
  lib/apis/v3/networkpolicy.go
Labels: docs-not-required, release-note-not-required

#1155 Selector field not required
  Makefile
  lib/apis/v3/globalnetworkpolicy.go
  lib/apis/v3/networkpolicy.go
Labels: docs-not-required, release-note-not-required

#1157 Automated cherry pick of #1152: correct string trim func usage
  lib/backend/model/block.go
Labels: docs-not-required, release-note-required

#1156 Automated cherry pick of #1152: correct string trim func usage
  lib/backend/model/block.go
Labels: docs-not-required, release-note-required

#1158 Add profile ids to networkset
  lib/backend/model/networkset.go
  lib/backend/syncersv1/felixsyncer/felixsyncer_e2e_test.go
  lib/backend/syncersv1/updateprocessors/networksetprocessor.go
  lib/backend/syncersv1/updateprocessors/networksetprocessor_test.go
Labels: docs-not-required, release-note-required

#1162 Update go-yaml-wrapper to switch to upstream go-yaml v2.2.5
  go.mod
  go.sum
Labels: docs-not-required, release-note-required

#1160 use declared variable kvps for return value
  lib/backend/k8s/resources/node.go
  lib/backend/k8s/resources/profile.go
Labels: docs-not-required, release-note-not-required

#1164 Use client-go@kubernetes-1.15.1 instead of client-go@v12.0.0 for go1.13
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#1169 Switch Makefile.common from wget to curl, remove wget dependency
  Makefile
Labels: docs-not-required, release-note-not-required

#1171 Set GOMOD_VENDOR=true for new check in Makefile.common
  Makefile
Labels: docs-not-required, release-note-not-required

#1168 Handle dual stack pod IPs
  go.mod
  go.sum
  lib/backend/k8s/conversion/constants.go
  lib/backend/k8s/conversion/conversion.go
  lib/backend/k8s/conversion/conversion_test.go
  lib/backend/k8s/k8s_test.go
  lib/backend/k8s/resources/workloadendpoint.go
Labels: docs-pr-required, release-note-required
