Repository projectcalico/libcalico-go, pull requests merged in 2019-12, with the labels that each got.

#1172 Fix static-checks
  Makefile
Labels: docs-not-required, release-note-not-required

#1165 fix some annotation typo
  lib/apis/v3/ipam_block.go
  lib/apis/v3/ipam_config.go
  lib/apis/v3/ipam_handle.go
  lib/apis/v3/ippool.go
  lib/backend/api/api.go
  lib/backend/etcdv3/etcdv3.go
  lib/backend/k8s/conversion/conversion_test.go
  lib/client/hostendpoint.go
  lib/clientv3/ippool.go
  lib/clientv3/ippool_e2e_test.go
  lib/converter/ippool.go
  lib/ipam/ipam_test.go
  lib/net/ip.go
  lib/net/ipnet.go
  lib/validator/v3/validator_test.go
  test/mock-node.yaml
Labels: docs-not-required, release-note-not-required

#1176 move all k8s.io packages to kubernetes v1.16.3
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#1175 fix validate
  lib/apis/v3/globalnetworkpolicy.go
Labels: docs-pr-required, release-note-required

#1177 fix: add err check before further operation
  lib/ipam/ipam.go
Labels: docs-not-required, release-note-not-required

#1179 Allow SCTP ports on api v3
  lib/numorstring/protocol.go
  lib/validator/v3/validator.go
  lib/validator/v3/validator_test.go
Labels: docs-pr-required, release-note-required

#1180 Revert "Allow SCTP ports on api v3"
  lib/numorstring/protocol.go
  lib/validator/v3/validator.go
  lib/validator/v3/validator_test.go
Labels: docs-not-required, release-note-not-required

#1182 SCTP ports
  lib/numorstring/protocol.go
  lib/validator/v1/validator.go
  lib/validator/v1/validator_test.go
  lib/validator/v3/validator.go
  lib/validator/v3/validator_test.go
Labels: docs-pr-required, release-note-required

#1183 Refactor errorThreshold to fix data race
  lib/backend/watchersyncer/watchercache.go
  lib/backend/watchersyncer/watchersyncer_test.go
Labels: docs-not-required, release-note-not-required

#1184 Update etcd version to pull in bug fixes
  go.mod
  go.sum
Labels: docs-not-required, release-note-required

#1185 Add 'Makefile.common*' to .gitignore
  .gitignore
Labels: docs-not-required, release-note-not-required

#1186 release-v3.10 - Cherry-pick go-yaml update
  go.mod
  go.sum
Labels: docs-not-required, release-note-required

#1187 release-v3.9 - Cherry-pick of go-yaml update
  go.mod
  go.sum
Labels: docs-not-required, release-note-required

#1188 release-v3.8 - Update go-yaml-wrapper so that we use go-yaml v2.25
  glide.lock
Labels: docs-not-required, release-note-required
