Repository projectcalico/libcalico-go, pull requests merged in 2019-05, with the labels that each got.

#1083 Increase K8S version to 1.14.1
  Makefile
  lib/backend/syncersv1/felixsyncer/felixsyncer_e2e_test.go
Labels: docs-not-required, release-note-not-required

#1086 Add etcd SRV discovery support
  Makefile
  lib/apiconfig/apiconfig.go
  lib/apis/v1/apiconfig.go
  lib/backend/etcd/etcd.go
  lib/backend/etcdv3/etcdv3.go
  lib/backend/etcdv3/etcdv3_test.go
  lib/client/client_test.go
  test/coredns/Corefile
  test/coredns/zones/etcd.zone
Labels: docs-pr-required, release-note-required

#1087 IPAM utilization reporting
  lib/backend/model/block.go
  lib/clientv3/client.go
  lib/clientv3/ippool.go
  lib/ipam/interface.go
  lib/ipam/ipam.go
  lib/ipam/ipam_block_reader_writer.go
  lib/ipam/ipam_test.go
  lib/ipam/ipam_types.go
  lib/ipam/pools.go
Labels: docs-pr-required, release-note-required

#1088 Update should set defaults before doing validation
  lib/clientv3/ippool.go
  lib/clientv3/ippool_e2e_test.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required
