Repository projectcalico/libcalico-go, pull requests merged in 2019-04, with the labels that each got.

#1065 Datamodel for VXLAN encapsulation support
  lib/apis/v1/ippool.go
  lib/apis/v3/felixconfig.go
  lib/apis/v3/ippool.go
  lib/apis/v3/node.go
  lib/apis/v3/zz_generated.deepcopy.go
  lib/backend/encap/doc.go
  lib/backend/encap/ipip.go
  lib/backend/k8s/resources/ippool.go
  lib/backend/k8s/resources/node.go
  lib/backend/model/block.go
  lib/backend/model/ippool.go
  lib/backend/syncersv1/bgpsyncer/bgpsyncer_e2e_test.go
  lib/backend/syncersv1/felixsyncer/felixsyncer_e2e_test.go
  lib/backend/syncersv1/felixsyncer/felixsyncerv1.go
  lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  lib/backend/syncersv1/updateprocessors/felixnodeprocessor.go
  lib/backend/syncersv1/updateprocessors/felixnodeprocessor_test.go
  lib/backend/syncersv1/updateprocessors/ippoolprocessor.go
  lib/backend/syncersv1/updateprocessors/ippoolprocessor_test.go
  lib/clientv3/common_test.go
  lib/clientv3/ippool.go
  lib/clientv3/ippool_e2e_test.go
  lib/clientv3/ippool_kdd_conversion_test.go
  lib/clientv3/node_e2e_test.go
  lib/converter/ippool.go
  lib/ipam/ipam.go
  lib/upgrade/converters/ippool.go
  lib/upgrade/converters/ippool_test.go
  lib/validator/v3/validator.go
  lib/validator/v3/validator_test.go
Labels: release-note-required

#1064 Improve health reporting
  lib/health/health.go
Labels: release-note-required

#1067 Fix migration code for VXLAN changes
  lib/upgrade/converters/ippool.go
  lib/upgrade/converters/ippool_test.go
Labels: docs-not-required, release-note-not-required

#1068 Add new Felix configuration parameters
  lib/apis/v3/felixconfig.go
  lib/apis/v3/zz_generated.deepcopy.go
  lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
Labels: docs-pr-required, release-note-required

#1069 Move IPAM block utilities to the model struct.
  lib/backend/model/block.go
  lib/backend/model/block_test.go
  lib/ipam/ipam.go
  lib/ipam/ipam_block.go
  lib/ipam/ipam_block_reader_writer.go
  lib/net/ip.go
Labels: docs-not-required, release-note-not-required

#1073 Fix that KeyFromDefaultPath didn't support IPAM blocks.
  lib/backend/model/keys.go
  lib/testutils/syncertester.go
Labels: docs-pr-required, release-note-required

#1074 Switch libcalico-go to use calico fork of logrus
  glide.lock
  glide.yaml
Labels: docs-pr-required, release-note-required

#1076 Clean-up delete failed etcdv3 message and Readme
  README.md
  lib/backend/etcdv3/etcdv3.go
Labels: docs-not-required, release-note-not-required

#1077 Reinstate host-local IPAM aggregation
  lib/apiconfig/apiconfig.go
  lib/backend/k8s/k8s.go
  lib/backend/k8s/k8s_test.go
  lib/backend/k8s/resources/ipam_block.go
  lib/backend/k8s/resources/ipam_block_pod_cidr.go
  lib/backend/k8s/resources/node.go
  lib/backend/k8s/resources/node_test.go
  lib/backend/syncersv1/felixsyncer/felixsyncer_e2e_test.go
  lib/backend/syncersv1/felixsyncer/felixsyncerv1.go
Labels: cherry-pick-candidate, docs-pr-required, release-note-required

#1078 Return error on failed Node list
  lib/backend/k8s/resources/node.go
Labels: docs-not-required, release-note-required

#1079 Return error on failed Node list
  lib/backend/k8s/resources/node.go
Labels: docs-not-required, release-note-required

#1080 Reject VXLAN and IPv6
  lib/clientv3/ippool_kdd_conversion_test.go
  lib/validator/v3/validator.go
  lib/validator/v3/validator_test.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#1081 Automated cherry pick of #1080: Reject VXLAN and IPv6
  lib/clientv3/ippool_kdd_conversion_test.go
  lib/validator/v3/validator.go
  lib/validator/v3/validator_test.go
Labels: docs-not-required, release-note-not-required
