Repository projectcalico/libcalico-go, pull requests merged in 2019-08, with the labels that each got.

#1097 Add DeviceRouteSourceAddress option to FelixConfig
  lib/apis/v3/felixconfig.go
  lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  lib/validator/v3/validator.go
  lib/validator/v3/validator_test.go
Labels: docs-pr-required, release-note-required

#1113 Fix logutils filename calculation.
  lib/logutils/benchmarks_test.go
  lib/logutils/logutils.go
Labels: docs-pr-required, release-note-required

#1114 Allow CrossSubnet value for IPPool resource's VXLANMode option
  lib/backend/syncersv1/updateprocessors/ippoolprocessor.go
  lib/backend/syncersv1/updateprocessors/ippoolprocessor_test.go
  lib/validator/v3/validator.go
  lib/validator/v3/validator_test.go
Labels: docs-pr-required, release-note-required

#1115 Send entire node in FelixNodeUpdateProcessor
  lib/backend/syncersv1/felixsyncer/felixsyncer_e2e_test.go
  lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  lib/backend/syncersv1/updateprocessors/felixnodeprocessor.go
  lib/backend/syncersv1/updateprocessors/felixnodeprocessor_test.go
Labels: docs-not-required, release-note-not-required

#1107 Remove NotNets array initialization
  lib/backend/k8s/conversion/conversion.go
  lib/backend/k8s/conversion/conversion_test.go
Labels: docs-not-required, release-note-required

#1111 Release IPIP and VXLAN addresses on node deletion
  lib/clientv3/node.go
  lib/clientv3/node_e2e_test.go
Labels: cherry-pick-candidate, docs-not-required, release-note-required

#1110 Switch to go modules from glide
  Makefile
  fakefile
  glide.lock
  glide.yaml
  go.mod
  go.sum
  lib/backend/etcd/etcd.go
  lib/backend/model/keys.go
  lib/backend/syncersv1/updateprocessors/configurationprocessor.go
  lib/backend/watchersyncer/watchersyncer_test.go
  lib/clientv3/client.go
  lib/clientv3/resources.go
  lib/errors/errors_test.go
  lib/ipam/ipam_block_reader_writer.go
  lib/ipam/pools.go
  lib/ipam/randomblock_test.go
  lib/logutils/logutils.go
  lib/testutils/resources.go
  lib/upgrade/converters/bgppeer.go
  lib/upgrade/converters/bgppeer_test.go
  lib/upgrade/converters/converter.go
  lib/upgrade/converters/hostendpoint_test.go
  lib/upgrade/converters/node_test.go
  lib/upgrade/converters/policy_test.go
  lib/upgrade/converters/profile_test.go
  lib/upgrade/converters/workloadendpoint.go
  lib/upgrade/converters/workloadendpoint_test.go
  lib/upgrade/migrator/migrate_test.go
  test/test.go
  tools.go
Labels: docs-not-required, release-note-not-required

#1119 Add settings for route protocol and disabling external route removal
  lib/apis/v3/felixconfig.go
  lib/apis/v3/zz_generated.deepcopy.go
  lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
Labels: docs-pr-required, release-note-required

#1121 Define GOPATH for go modules cachine when it is not specified by the environment
  Makefile
Labels: docs-not-required, release-note-not-required
