Repository projectcalico/libcalico-go, pull requests merged in 2019-07, with the labels that each got.

#1104 ipam GetAssignmentAttributes to return correct error code.
  lib/ipam/ipam.go
  lib/ipam/ipam_block.go
  lib/ipam/ipam_test.go
Labels: docs-pr-required, release-note-required

#1103 Clean up watches in k8s_test.go
  lib/backend/k8s/k8s_test.go
Labels: docs-not-required, release-note-not-required

#1102 Add config option for iptables backend
  lib/apis/v3/felixconfig.go
  lib/apis/v3/zz_generated.deepcopy.go
  lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  lib/validator/v3/validator.go
Labels: docs-pr-required, release-note-required

#1105 [v3.8] Add config option for iptables backend
  lib/apis/v3/felixconfig.go
  lib/apis/v3/zz_generated.deepcopy.go
  lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  lib/validator/v3/validator.go
Labels: docs-pr-required, release-note-required

#1106 Make the Prometheus host a configurable property
  lib/apis/v3/felixconfig.go
  lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  lib/validator/v3/validator.go
  lib/validator/v3/validator_test.go
Labels: docs-pr-required, release-note-required

#1108 Revised the doc. Default value for prometheus host: empty
  lib/apis/v3/felixconfig.go
Labels: docs-completed, release-note-required

#1109 Use join host port, so we can validate inputs more effectively
  lib/health/health.go
Labels: docs-pr-required, release-note-required
