Repository projectcalico/libcalico-go, pull requests merged in 2019-09, with the labels that each got.

#1124 Replace logrus pseudo version with a real one
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#1126 Fix logging to be independent of go mod versions
  go.sum
  lib/logutils/logutils.go
Labels: docs-pr-required, release-note-required

#1127 Fix logging to be independent of go mod versions
  lib/logutils/logutils.go
Labels: docs-pr-required, release-note-required

#1128 Replace logrus pseudo version with a real one
  go.mod
Labels: docs-not-required, release-note-not-required

#1129 Ignore Windows reserved addresses
  lib/ipam/ipam_block.go
Labels: cherry-pick-candidate, docs-not-required, release-note-required

#1130 Automated cherry pick of #1129: Ignore Windows reserved addresses
  lib/ipam/ipam_block.go
Labels: docs-not-required, release-note-required

#1123 BGPConfiguration: ServiceExternalIPs Field
  lib/apis/v3/bgpconfig.go
  lib/apis/v3/zz_generated.deepcopy.go
  lib/backend/syncersv1/updateprocessors/bgpconfigprocessor.go
  lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  lib/clientv3/bgpconfig.go
  lib/clientv3/bgpconfig_e2e_test.go
Labels: docs-pr-required, release-note-required

#1131 Use Kubernetes 1.16 in tests
  Makefile
Labels: docs-not-required, release-note-not-required

#1134 Expose ClusterIP advertisement through BGP configuration
  lib/apis/v3/bgpconfig.go
  lib/apis/v3/zz_generated.deepcopy.go
  lib/backend/syncersv1/updateprocessors/bgpconfigprocessor.go
  lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  lib/clientv3/bgpconfig.go
  lib/clientv3/bgpconfig_e2e_test.go
Labels: docs-pr-required, release-note-required

#1132 cleanup: fix some code warnings
  lib/backend/client.go
  lib/numorstring/protocol.go
  lib/upgrade/converters/rule.go
  lib/upgrade/migrator/felixconfig.go
  lib/upgrade/migrator/migrate.go
Labels: docs-not-required, release-note-not-required
