Repository projectcalico/libcalico-go, pull requests merged in 2019-06, with the labels that each got.

#1092 Fix IPPool creation with host-local IPAM and KDD
  lib/clientv3/ippool.go
Labels: docs-pr-required, release-note-required

#1090 Added code and tests to provide config for vxlan MAC.
  lib/apis/v3/node.go
  lib/backend/k8s/resources/node.go
  lib/backend/syncersv1/felixsyncer/felixsyncer_e2e_test.go
  lib/backend/syncersv1/updateprocessors/felixnodeprocessor.go
  lib/backend/syncersv1/updateprocessors/felixnodeprocessor_test.go
  lib/validator/v3/validator.go
Labels: docs-pr-required, release-note-required

#1093 felixconfig: add sockmap config param
  lib/apis/v3/felixconfig.go
  lib/apis/v3/zz_generated.deepcopy.go
  lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
Labels: docs-pr-required, release-note-required

#1094 Don't run CoreDNS with host networking
  Makefile
Labels: docs-not-required, release-note-not-required

#1095 Automated cherry pick of #1088: Update should set defaults before doing validation
  lib/clientv3/ippool.go
  lib/clientv3/ippool_e2e_test.go
Labels: docs-not-required, release-note-required

#1096 Lowercase the field NATOutgoingAddress
  lib/apis/v3/felixconfig.go
  lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
Labels: docs-not-required, release-note-not-required

#1098 Rename SockmapEnabled to SidecarAccelerationEnabled.
  lib/apis/v3/felixconfig.go
  lib/apis/v3/zz_generated.deepcopy.go
Labels: docs-completed, release-note-not-required

#1099 Rename SockmapEnabled to SidecarAccelerationEnabled.
  lib/apis/v3/felixconfig.go
  lib/apis/v3/zz_generated.deepcopy.go
Labels: docs-completed, release-note-not-required

#1075 Improve health report diags
  lib/health/health.go
Labels: docs-not-required, release-note-not-required

#1100 felixsyncer_e2e_test.go: don't leak Node changes into other tests
  lib/backend/syncersv1/felixsyncer/felixsyncer_e2e_test.go
Labels: docs-pr-required, release-note-required

#1101 felixsyncer_e2e_test.go: don't leak Node changes into other tests
  lib/backend/syncersv1/felixsyncer/felixsyncer_e2e_test.go
Labels: docs-pr-required, release-note-required

#1091 BGPPeer invalid selector fix
  lib/apis/v3/bgppeer.go
  lib/validator/v3/validator_test.go
Labels: docs-not-required, release-note-required
