Repository projectcalico/libcalico-go, pull requests merged in 2019-01, with the labels that each got.

#993 Add NodeSelector to IP pools
  lib/apis/v3/ippool.go
  lib/backend/syncersv1/bgpsyncer/bgpsyncer_e2e_test.go
  lib/clientv3/common_test.go
  lib/clientv3/ippool.go
  lib/clientv3/ippool_e2e_test.go
  lib/clientv3/ippool_kdd_conversion_test.go
  lib/ipam/ipam.go
  lib/ipam/ipam_block.go
  lib/ipam/ipam_block_reader_writer_test.go
  lib/ipam/ipam_test.go
  lib/validator/v3/validator_test.go
Labels: release-note-required

#999 Release affinities when IP pools no longer select the node
  lib/ipam/ipam.go
  lib/ipam/ipam_block_reader_writer.go
  lib/ipam/ipam_test.go
Labels: cherry-pick-candidate

#1002 IPAM: ensure that empty blocks affinities when ip pool deselects the node
  lib/ipam/ipam.go
  lib/ipam/ipam_block_reader_writer.go
  lib/ipam/ipam_block_reader_writer_test.go
  lib/ipam/ipam_test.go
Labels: cherry-pick-candidate

#994 Support status reporting across multiple OpenStack regions
  lib/backend/clean_e2e_test.go
  lib/backend/model/keys.go
  lib/backend/model/keys_test.go
  lib/backend/model/region.go
  lib/backend/model/statusreports.go
  lib/backend/model/workloadendpointstatus.go
Labels: cherry-pick-candidate, release-note-required

#1003 Let Calico Nodes inherit labels from Kubernetes Nodes
  lib/backend/k8s/resources/node.go
  lib/backend/k8s/resources/node_test.go
Labels: cherry-pick-candidate

#1004 Don't error if the IPAM host doesn't exist
  lib/ipam/ipam.go
  lib/ipam/ipam_test.go
Labels: cherry-pick-candidate
