Repository projectcalico/libcalico-go, pull requests merged in 2019-10, with the labels that each got.

#1133 new selectors for NP and GNP
  lib/apis/v3/globalnetworkpolicy.go
  lib/apis/v3/networkpolicy.go
  lib/apis/v3/networkpolicy_test.go
  lib/backend/model/policy_test.go
  lib/backend/syncersv1/updateprocessors/globalnetworkpolicyprocessor.go
  lib/backend/syncersv1/updateprocessors/globalnetworkpolicyprocessor_test.go
  lib/backend/syncersv1/updateprocessors/networkpolicyprocessor.go
  lib/backend/syncersv1/updateprocessors/networkpolicyprocessor_test.go
  lib/backend/syncersv1/updateprocessors/rules.go
  lib/backend/syncersv1/updateprocessors/selectors.go
  lib/backend/syncersv1/updateprocessors/shared_test.go
Labels: docs-pr-required, release-note-required

#1136 Validate BGP serviceClusterIPs and serviceExternalIPs fields
  lib/apis/v3/bgpconfig.go
  lib/validator/v3/validator_test.go
Labels: docs-not-required, release-note-not-required

#1135 Combine together ports of the same protocol
  lib/backend/k8s/conversion/conversion.go
  lib/backend/k8s/conversion/conversion_test.go
Labels: docs-not-required, release-note-required

#1137 need to harden go mod downloads against network errors
  Makefile
Labels: docs-not-required, release-note-not-required

#1138 Update client-go to v12.0.0
  go.mod
  go.sum
  lib/apis/v3/zz_generated.deepcopy.go
  lib/upgrade/migrator/clients/v1/k8s/custom/zz_generated.deepcopy.go
Labels: docs-not-required, release-note-required

#1140 Update client-go to v12.0.0
  go.mod
  go.sum
  lib/apis/v3/zz_generated.deepcopy.go
  lib/upgrade/migrator/clients/v1/k8s/custom/zz_generated.deepcopy.go
Labels: docs-not-required, release-note-required

#1144 Fix client-go updates
  go.mod
  go.sum
  lib/backend/k8s/k8s.go
  lib/upgrade/migrator/clients/v1/k8s/k8s.go
Labels: docs-not-required, release-note-not-required

#1145 Fix renamed serializer variable
  lib/backend/k8s/k8s.go
  lib/upgrade/migrator/clients/v1/k8s/k8s.go
Labels: docs-not-required, release-note-not-required

#1139 Update client-go to v12.0.0
  go.mod
  go.sum
  lib/apis/v3/zz_generated.deepcopy.go
  lib/backend/k8s/k8s.go
  lib/upgrade/migrator/clients/v1/k8s/custom/zz_generated.deepcopy.go
  lib/upgrade/migrator/clients/v1/k8s/k8s.go
Labels: docs-not-required, release-note-required

#1141 Update client-go to v12.0.0
  glide.lock
  glide.yaml
  lib/apis/v3/zz_generated.deepcopy.go
  lib/backend/k8s/k8s.go
  lib/upgrade/migrator/clients/v1/k8s/custom/zz_generated.deepcopy.go
  lib/upgrade/migrator/clients/v1/k8s/k8s.go
Labels: docs-not-required, release-note-required

#1142 Update client-go to v12.0.0
  glide.lock
  glide.yaml
  lib/apis/v3/zz_generated.deepcopy.go
  lib/backend/k8s/k8s.go
  lib/upgrade/migrator/clients/v1/k8s/custom/zz_generated.deepcopy.go
  lib/upgrade/migrator/clients/v1/k8s/k8s.go
Labels: docs-not-required, release-note-required

#1149 cleanup code, call String() instead of fmt.Sprintf
  lib/ipam/ipam_block_reader_writer_test.go
Labels: docs-pr-required, release-note-required

#1150 fix struct definition error in v3
  lib/apis/v3/ipam_block.go
Labels: docs-not-required, release-note-not-required

#1151 Revert "Update client-go to v12.0.0"
  glide.lock
  glide.yaml
  lib/apis/v3/zz_generated.deepcopy.go
  lib/backend/k8s/k8s.go
  lib/upgrade/migrator/clients/v1/k8s/custom/zz_generated.deepcopy.go
  lib/upgrade/migrator/clients/v1/k8s/k8s.go
Labels: docs-not-required, release-note-not-required

#1152 fix: correct string trim func usage
  lib/backend/model/block.go
Labels: docs-not-required, release-note-required
