Repository projectcalico/libcalico-go, pull requests merged in 2020-12, with the labels that each got.

#1351 Add BGPPeer SourceAddress field
  config/crd/crd.projectcalico.org_bgppeers.yaml
  lib/apis/v3/bgppeer.go
  lib/validator/v1/validator.go
  lib/validator/v3/validator.go
  lib/validator/v3/validator_test.go
Labels: docs-pr-required, release-note-required

#1350 replaces unicode quotation marks in code comments with ascii double quotes
  config/crd/crd.projectcalico.org_felixconfigurations.yaml
  config/crd/crd.projectcalico.org_globalnetworkpolicies.yaml
  config/crd/crd.projectcalico.org_hostendpoints.yaml
  config/crd/crd.projectcalico.org_networkpolicies.yaml
  lib/apis/v1/hostendpoint.go
  lib/apis/v1/policy.go
  lib/apis/v1/profile.go
  lib/apis/v1/rule.go
  lib/apis/v1/workloadendpoint.go
  lib/apis/v3/felixconfig.go
  lib/apis/v3/globalnetworkpolicy.go
  lib/apis/v3/hostendpoint.go
  lib/apis/v3/policy.go
Labels: docs-pr-required, merge-when-ready, release-note-not-required

#1349 Add configuration option for advertising LB IPs
  config/crd/crd.projectcalico.org_bgpconfigurations.yaml
  lib/apis/v3/bgpconfig.go
  lib/apis/v3/zz_generated.deepcopy.go
  lib/clientv3/bgpconfig.go
  lib/clientv3/bgpconfig_e2e_test.go
Labels: docs-pr-required, release-note-required

#1353 Remove bgppeer KeepOriginalNextHop default
  config/crd/crd.projectcalico.org_bgppeers.yaml
  lib/apis/v3/bgppeer.go
Labels: docs-pr-required, release-note-required

#1354 Automated cherry pick of #1353 upstream release v3.17
  config/crd/crd.projectcalico.org_bgppeers.yaml
  lib/apis/v3/bgppeer.go
Labels: docs-not-required, release-note-not-required
