Repository projectcalico/libcalico-go, pull requests merged in 2020-07, with the labels that each got.

#1264 Added felix config param; FeatureDetectOverride
  config/crd/crd.projectcalico.org_felixconfigurations.yaml
  lib/apis/v3/felixconfig.go
  lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  lib/validator/v3/validator.go
Labels: docs-pr-required, release-note-required

#1268 Have make patch crd instead of doing manually
  Makefile
  config.patch
Labels: docs-not-required, release-note-not-required

#1262 BGP communities and configurable BGP port
  config/crd/crd.projectcalico.org_bgpconfigurations.yaml
  config/crd/crd.projectcalico.org_bgppeers.yaml
  lib/apis/v3/bgpconfig.go
  lib/apis/v3/bgppeer.go
  lib/apis/v3/zz_generated.deepcopy.go
  lib/backend/model/keys.go
  lib/backend/syncersv1/bgpsyncer/bgpsyncer.go
  lib/backend/syncersv1/bgpsyncer/bgpsyncer_e2e_test.go
  lib/backend/syncersv1/updateprocessors/bgpconfigprocessor.go
  lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  lib/clientv3/bgpconfig.go
  lib/validator/v3/validator.go
  lib/validator/v3/validator_test.go
Labels: docs-pr-required, release-note-required

#1266 Maintaining original next hop on specific bgppeer
  config/crd/crd.projectcalico.org_bgppeers.yaml
  lib/apis/v3/bgppeer.go
Labels: docs-pr-required, release-note-required

#1263 Fix typo across codebase
  config/crd/crd.projectcalico.org_ippools.yaml
  docs/data-model.md
  lib/apis/v3/ippool.go
  lib/backend/api/api.go
  lib/backend/k8s/k8s.go
  lib/backend/k8s/k8s_test.go
  lib/backend/model/keys_test.go
  lib/backend/syncersv1/bgpsyncer/bgpsyncer_e2e_test.go
  lib/clientv3/ippool_e2e_test.go
  lib/clientv3/node_e2e_test.go
  lib/errors/errors.go
  lib/ipam/ipam_block_reader_writer.go
  lib/names/workloadendpoint.go
Labels: docs-pr-required, release-note-required

#1269 Support peer with same IP but different port
  lib/apis/v3/bgpconfig.go
  lib/backend/model/bgppeer.go
  lib/backend/model/bgppeer_test.go
  lib/backend/model/keys.go
  lib/backend/syncersv1/bgpsyncer/bgpsyncer.go
  lib/backend/syncersv1/bgpsyncer/bgpsyncer_e2e_test.go
  lib/clientv3/bgpconfig.go
  lib/validator/v3/validator_test.go
Labels: docs-pr-required, release-note-required

#1270 Add felix config param: InterfaceRefreshInterval.
  config/crd/crd.projectcalico.org_bgppeers.yaml
  config/crd/crd.projectcalico.org_felixconfigurations.yaml
  lib/apis/v3/felixconfig.go
  lib/apis/v3/zz_generated.deepcopy.go
  lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
Labels: docs-pr-required, release-note-not-required

#1247 Handle backend watch, if upstream closes channel[ClosedByRemote]
  lib/backend/api/api.go
  lib/backend/etcdv3/watcher.go
  lib/backend/k8s/resources/networkpolicy.go
  lib/backend/k8s/resources/profile.go
  lib/backend/k8s/resources/watcher.go
  lib/backend/watchersyncer/watchercache.go
  lib/backend/watchersyncer/watchersyncer_test.go
Labels: docs-not-required, release-note-required

#1271 Upgrade to golang 1.14
  Makefile
  go.mod
  lib/apis/crd.projectcalico.org/v1/bgpconfig_types.go
  lib/apis/crd.projectcalico.org/v1/bgppeer_types.go
  lib/apis/crd.projectcalico.org/v1/block_affinity_types.go
  lib/apis/crd.projectcalico.org/v1/clusterinformation_types.go
  lib/apis/crd.projectcalico.org/v1/felixconfiguration_types.go
  lib/apis/crd.projectcalico.org/v1/globalnetworkpolicy_types.go
  lib/apis/crd.projectcalico.org/v1/globalnetworkset_types.go
  lib/apis/crd.projectcalico.org/v1/hostendpoint_types.go
  lib/apis/crd.projectcalico.org/v1/ipamblock_types.go
  lib/apis/crd.projectcalico.org/v1/ipamconfig_types.go
  lib/apis/crd.projectcalico.org/v1/ipamhandle_types.go
  lib/apis/crd.projectcalico.org/v1/ippool_types.go
  lib/apis/crd.projectcalico.org/v1/kubecontrollersconfiguration_types.go
  lib/apis/crd.projectcalico.org/v1/networkpolicy_types.go
  lib/apis/crd.projectcalico.org/v1/networkset_types.go
  lib/backend/k8s/resources/node_test.go
  lib/upgrade/converters/node_test.go
Labels: docs-not-required, release-note-required

#1272 Additional validation for BGP communities
  lib/validator/v3/validator.go
  lib/validator/v3/validator_test.go
Labels: docs-pr-required, release-note-required
