Repository projectcalico/libcalico-go, pull requests merged in 2020-09, with the labels that each got.

#1292 Add test for releasing borrowed IP.
  lib/ipam/ipam_test.go
Labels: docs-not-required, release-note-not-required

#1293 Update BGPPeer required fields
  config/crd/crd.projectcalico.org_bgppeers.yaml
  lib/apis/v3/bgppeer.go
Labels: docs-pr-required, release-note-not-required

#1296 Add new FelixConfiguration knobs for disabling encap drop rules
  config/crd/crd.projectcalico.org_felixconfigurations.yaml
  lib/apis/v3/felixconfig.go
  lib/apis/v3/zz_generated.deepcopy.go
  lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
Labels: docs-pr-required, release-note-required

#1298 Add kubebuilder markers to FelixConfiguration encap knobs
  lib/apis/v3/felixconfig.go
Labels: docs-pr-required, release-note-not-required

#1299 Attempt to release other blocks even if one isn't empty
  lib/ipam/ipam.go
  lib/ipam/ipam_test.go
Labels: docs-pr-required, release-note-required

#1301 Automated cherry pick of #1296: Add new FelixConfiguration knobs for disabling encap drop #1298: Add kubebuilder markers to FelixConfiguration encap knobs
  config/crd/crd.projectcalico.org_felixconfigurations.yaml
  lib/apis/v3/felixconfig.go
  lib/apis/v3/zz_generated.deepcopy.go
  lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
Labels: docs-pr-required, release-note-required

#1302 Automated cherry pick of #1296: Add new FelixConfiguration knobs for disabling encap drop #1298: Add kubebuilder markers to FelixConfiguration encap knobs
  config/crd/crd.projectcalico.org_felixconfigurations.yaml
  lib/apis/v3/felixconfig.go
  lib/apis/v3/zz_generated.deepcopy.go
  lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
Labels: docs-pr-required, release-note-required

#1300 Allow host affinity release even if pool doesn't exist
  lib/ipam/ipam.go
  lib/ipam/ipam_test.go
Labels: docs-pr-required, release-note-required

#1297 Configure max blocks per-host in IPAMConfig
  config/crd/crd.projectcalico.org_ipamconfigs.yaml
  lib/apis/v3/ipam_config.go
  lib/backend/k8s/resources/ipam_config.go
  lib/backend/model/ipam_config.go
  lib/ipam/ipam.go
  lib/ipam/ipam_test.go
  lib/ipam/ipam_types.go
Labels: docs-pr-required, release-note-required

#1279 Change default datastoretype
  lib/apiconfig/apiconfig.go
  lib/apiconfig/load.go
Labels: docs-pr-required, release-note-required

#1306 Handle explicit k8s API endpoint in kube config
  lib/apiconfig/load.go
Labels: docs-not-required, release-note-not-required

#1310 Cleanup wireguard tunnel address
  lib/clientv3/node.go
Labels: docs-not-required, release-note-required

#1312 Restore defaulting to LoadConfigFromXXX methods.
  lib/apiconfig/load.go
Labels: docs-not-required, release-note-not-required

#1313 Fix defaulting of config params when in a scratch container.
  lib/apiconfig/load.go
Labels: docs-not-required, release-note-not-required

#1315 Trigger update pin pipelines in typha on successful master / release …
  .semaphore/semaphore.yml
  Makefile
Labels: docs-not-required, release-note-not-required

#1304 remove spurious annotations and creationtimestamps from crds
  config.patch
  config/crd/crd.projectcalico.org_bgpconfigurations.yaml
  config/crd/crd.projectcalico.org_bgppeers.yaml
  config/crd/crd.projectcalico.org_blockaffinities.yaml
  config/crd/crd.projectcalico.org_clusterinformations.yaml
  config/crd/crd.projectcalico.org_felixconfigurations.yaml
  config/crd/crd.projectcalico.org_globalnetworkpolicies.yaml
  config/crd/crd.projectcalico.org_globalnetworksets.yaml
  config/crd/crd.projectcalico.org_hostendpoints.yaml
  config/crd/crd.projectcalico.org_ipamblocks.yaml
  config/crd/crd.projectcalico.org_ipamconfigs.yaml
  config/crd/crd.projectcalico.org_ipamhandles.yaml
  config/crd/crd.projectcalico.org_ippools.yaml
  config/crd/crd.projectcalico.org_kubecontrollersconfigurations.yaml
  config/crd/crd.projectcalico.org_networkpolicies.yaml
  config/crd/crd.projectcalico.org_networksets.yaml
Labels: docs-not-required, release-note-not-required

#1317 delete common makefiles on clean
  Makefile
Labels: docs-not-required, merge-when-ready, release-note-not-required

#1316 Update go-build version to v0.48 (go 1.15.2)
  Makefile
Labels: docs-not-required, release-note-not-required

#1320 Fix recrusive Error() call for ErrorValidation struct
  lib/errors/errors.go
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1319 Add more projects to update pins when triggering the auto pin update
  Makefile
Labels: docs-not-required, release-note-not-required

#1322 Add Password field to BGPPeer
  config/crd/crd.projectcalico.org_bgppeers.yaml
  lib/apis/v3/bgppeer.go
  lib/apis/v3/zz_generated.deepcopy.go
  lib/clientv3/bgppeer_e2e_test.go
  lib/validator/v3/validator_test.go
Labels: docs-pr-required, release-note-required

#1323 Update go.mod to golang 1.15 and update ginkgo / gomega libraries
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#1324 Node.Addresses list all address at which the node is reachable.
  lib/apis/v3/node.go
  lib/apis/v3/zz_generated.deepcopy.go
  lib/backend/k8s/resources/node.go
  lib/backend/k8s/resources/node_test.go
Labels: docs-pr-required, release-note-required
