Repository projectcalico/libcalico-go, pull requests merged in 2020-10, with the labels that each got.

#1303 Add ownerref / finalizer to IPAM handles
  lib/backend/k8s/k8s.go
  lib/backend/k8s/resources/customresource.go
  lib/backend/k8s/resources/ipam_handle.go
  lib/backend/k8s/resources/resources.go
  lib/backend/model/block.go
  lib/backend/model/ipam_handle.go
  lib/ipam/ipam.go
  lib/ipam/ipam_test.go
Labels: docs-not-required, release-note-required

#1321 Validate IPv6 external IP and cluster IP
  lib/validator/v3/validator_test.go
Labels: docs-not-required, release-note-not-required

#1326 Properly respect Deleted flag
  config/crd/crd.projectcalico.org_ipamhandles.yaml
  lib/apis/v3/ipam_handle.go
  lib/backend/k8s/resources/ipam_handle.go
  lib/backend/k8s/resources/ipam_handle_test.go
Labels: docs-not-required, release-note-not-required

#1327 Merge pull request #1322 from neiljerram/bgp-password-oss
  config/crd/crd.projectcalico.org_bgppeers.yaml
  lib/apis/v3/bgppeer.go
  lib/apis/v3/zz_generated.deepcopy.go
  lib/clientv3/bgppeer_e2e_test.go
  lib/validator/v3/validator_test.go
Labels: docs-not-required, release-note-not-required

#1328 Fix retry loop so it breaks on success
  lib/ipam/ipam.go
Labels: docs-not-required, release-note-not-required

#1275 assign ip from special ipv6 ippool and calico crashes
  lib/backend/model/block.go
  lib/ipam/ipam_block_reader_writer.go
  lib/net/ip.go
Labels: docs-not-required, release-note-required

#1330 Service loop prevention
  config/crd/crd.projectcalico.org_felixconfigurations.yaml
  go.mod
  go.sum
  lib/apis/v3/felixconfig.go
  lib/backend/model/block.go
  lib/backend/model/ipam_handle.go
  lib/backend/syncersv1/felixsyncer/felixsyncerv1.go
  lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  lib/net/ip.go
  lib/validator/v3/validator_test.go
Labels: docs-pr-required, release-note-required

#1318 Make deleted an optional field
  config/crd/crd.projectcalico.org_ipamblocks.yaml
  lib/apis/v3/ipam_block.go
Labels: docs-pr-required, release-note-required

#1333 Revert "Add ownerref / finalizer to IPAM handles (#1303)"
  lib/backend/k8s/k8s.go
  lib/backend/k8s/resources/customresource.go
  lib/backend/k8s/resources/ipam_handle.go
  lib/backend/k8s/resources/resources.go
  lib/backend/model/block.go
  lib/backend/model/ipam_handle.go
  lib/ipam/ipam.go
  lib/ipam/ipam_test.go
Labels: docs-not-required, release-note-not-required

#1334 updated default in doc for BPFDataIfacePattern
  config/crd/crd.projectcalico.org_felixconfigurations.yaml
  lib/apis/v3/felixconfig.go
  lib/backend/model/ipam_handle.go
Labels: docs-pr-required, release-note-required

#1331 Add field to configure interfaces for MTU detection
  config/crd/crd.projectcalico.org_felixconfigurations.yaml
  lib/apis/v3/felixconfig.go
  lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  lib/validator/v3/validator_test.go
Labels: docs-not-required, release-note-required

#1337 etcd backend not passing watcher errors up the stack, and errors not …
  lib/backend/etcdv3/watcher.go
  lib/backend/watchersyncer/watchercache.go
  lib/backend/watchersyncer/watchersyncer.go
  lib/backend/watchersyncer/watchersyncer_test.go
  lib/errors/errors.go
Labels: docs-pr-required, release-note-required

#1338 etcd backend not passing watcher errors up the stack, and errors not …
  lib/backend/etcdv3/watcher.go
  lib/backend/watchersyncer/watchercache.go
  lib/backend/watchersyncer/watchersyncer.go
  lib/backend/watchersyncer/watchersyncer_test.go
  lib/errors/errors.go
Labels: docs-pr-required, release-note-required
