Repository projectcalico/libcalico-go, pull requests merged in 2020-02, with the labels that each got.

#1193 Fix up noisy and unhelpful log
  lib/backend/k8s/resources/networkpolicy.go
Labels: docs-not-required, release-note-not-required

#1192 Fix revision numbers for NetworkPolicy watches
  lib/backend/k8s/conversion/conversion.go
  lib/backend/k8s/k8s_test.go
  lib/backend/k8s/resources/networkpolicy.go
Labels: docs-not-required, release-note-required

#1194 Drop log level for confusing logs
  lib/backend/k8s/k8s.go
Labels: docs-not-required, release-note-not-required

#1195 Add configuration values for BPF.
  lib/apis/v3/felixconfig.go
  lib/apis/v3/zz_generated.deepcopy.go
  lib/backend/k8s/k8s_test.go
  lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  lib/validator/v3/validator.go
  lib/validator/v3/validator_test.go
Labels: docs-pr-required, release-note-required
