Repository projectcalico/libcalico-go, pull requests merged in 2020-06, with the labels that each got.

#1244 Properly set deleted on block affinities
  config/crd/crd.projectcalico.org_blockaffinities.yaml
  config/crd/crd.projectcalico.org_felixconfigurations.yaml
  lib/apis/v3/blockaffinity.go
  lib/backend/k8s/resources/ipam_affinity.go
  lib/backend/k8s/resources/ipam_affinity_test.go
Labels: docs-not-required, release-note-required

#1246 update to k8s 1.17.2
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#1250 For host local IPAM use the first IP in the CIDR block for wireguard as well as IPIP
  lib/backend/k8s/resources/node.go
  lib/backend/k8s/resources/node_test.go
Labels: docs-not-required, release-note-not-required

#1252 Configuration model for active / passive felix implementation
  Makefile
  config/crd/crd.projectcalico.org_clusterinformations.yaml
  config/crd/crd.projectcalico.org_felixconfigurations.yaml
  lib/apis/v3/clusterinfo.go
  lib/backend/k8s/k8s_test.go
  lib/backend/syncersv1/felixsyncer/felixsyncer_e2e_test.go
  lib/backend/syncersv1/felixsyncer/felixsyncerv1.go
  lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
Labels: docs-pr-required, release-note-not-required

#1229 Add global() selector
  lib/apis/v3/policy.go
  lib/backend/syncersv1/updateprocessors/rules.go
  lib/backend/syncersv1/updateprocessors/rules_test.go
  lib/selector/parser/ast.go
  lib/selector/parser/parser.go
  lib/selector/parser/parser_test.go
  lib/selector/tokenizer/tokenizer.go
  lib/selector/tokenizer/tokenizer_test.go
  lib/validator/v3/validator.go
  lib/validator/v3/validator_test.go
Labels: docs-pr-required, release-note-required

#1253 Update generated crds for https://github.com/projectcalico/libcalico-…
  config/crd/crd.projectcalico.org_globalnetworkpolicies.yaml
  config/crd/crd.projectcalico.org_networkpolicies.yaml
Labels: docs-not-required, release-note-not-required

#1255 Revert config change for AWS EC2 src-dst-check
  config/crd/crd.projectcalico.org_felixconfigurations.yaml
  lib/apis/v3/felixconfig.go
  lib/apis/v3/zz_generated.deepcopy.go
  lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  lib/validator/v3/validator_test.go
Labels: docs-completed, release-note-not-required

#1248 Don't need to query blocks individually to see if they exist
  lib/ipam/ipam_block_reader_writer.go
Labels: docs-not-required, release-note-required

#1257 Add configurable QPS setting for the kube client
  lib/apiconfig/apiconfig.go
  lib/backend/k8s/k8s.go
Labels: docs-not-required, release-note-not-required

#1258 Add configurable QPS setting for the kube client
  lib/apiconfig/apiconfig.go
  lib/backend/k8s/k8s.go
Labels: docs-not-required, release-note-not-required

#1259 Fix wireguard IPv4 address capitalization
  lib/apis/v3/node.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#1260 Automated cherry pick of #1259: Fix wireguard IPv4 address capitalization
  lib/apis/v3/node.go
Labels: docs-pr-required, release-note-required
