Repository projectcalico/libcalico-go, pull requests merged in 2020-11, with the labels that each got.

#1339 [master] Automatic update of sempahore YAMLs.
  .semaphore/semaphore.yml
Labels: docs-pr-required, release-note-required

#1340 Fix release branch pin update regex (add ^ to start)
  .semaphore/semaphore.yml
  Makefile
Labels: docs-not-required, release-note-not-required

#1341 Remove confd pin update trigger (typha will do it)
  Makefile
Labels: docs-not-required, release-note-not-required

#1335 context support to k8s backend and apiconfig
  lib/apiconfig/apiconfig.go
  lib/backend/k8s/k8s.go
Labels: docs-pr-required, release-note-required

#1345 Handle malformed handle IDs
  lib/ipam/ipam.go
  lib/ipam/ipam_block.go
Labels: docs-not-required, release-note-required

#1344 update k8s to v0.18.12
  go.mod
  go.sum
  lib/backend/k8s/k8s.go
  lib/backend/k8s/k8s_test.go
  lib/backend/k8s/resources/customresource.go
  lib/backend/k8s/resources/networkpolicy.go
  lib/backend/k8s/resources/node.go
  lib/backend/k8s/resources/profile.go
  lib/backend/k8s/resources/workloadendpoint.go
  lib/backend/k8s/resources/workloadendpoint_test.go
  lib/ipam/ipam_test.go
  lib/upgrade/migrator/clients/v1/k8s/resources/customnoderesource.go
  lib/upgrade/migrator/clients/v1/k8s/resources/customresource.go
Labels: docs-not-required, release-note-not-required

#1346 Automated cherry pick of #1345: Handle malformed handle IDs
  lib/ipam/ipam.go
  lib/ipam/ipam_block.go
Labels: docs-not-required, release-note-required

#1347 Make deleted an optional field
  config/crd/crd.projectcalico.org_blockaffinities.yaml
  config/crd/crd.projectcalico.org_ipamblocks.yaml
  lib/apis/v3/blockaffinity.go
  lib/apis/v3/ipam_block.go
Labels: docs-not-required, release-note-not-required
