Repository projectcalico/libcalico-go, pull requests merged in 2020-05, with the labels that each got.

#1233 Fix k8sWatcherConverter to return error anytime the event has an error
  lib/backend/k8s/resources/watcher.go
  lib/backend/k8s/resources/watcher_test.go
Labels: docs-not-required, release-note-not-required

#1234 [Pick #1233 - r3.14] k8sWatcherConverter always returns one event for errors
  lib/backend/k8s/resources/watcher.go
  lib/backend/k8s/resources/watcher_test.go
Labels: docs-not-required, release-note-not-required

#1231 Refactor host-local IPAM support to use watches
  lib/apis/v3/node.go
  lib/apis/v3/zz_generated.deepcopy.go
  lib/backend/k8s/k8s.go
  lib/backend/k8s/resources/ipam_block_pod_cidr.go
  lib/backend/k8s/resources/node.go
  lib/backend/syncersv1/bgpsyncer/bgpsyncer.go
  lib/backend/syncersv1/bgpsyncer/bgpsyncer_e2e_test.go
  lib/backend/syncersv1/felixsyncer/felixsyncerv1.go
  lib/backend/syncersv1/updateprocessors/bgpnodeprocessor.go
  lib/backend/syncersv1/updateprocessors/bgpnodeprocessor_test.go
  lib/backend/syncersv1/updateprocessors/felixnodeprocessor.go
  lib/backend/syncersv1/updateprocessors/felixnodeprocessor_test.go
  lib/backend/syncersv1/updateprocessors/node_cidr_tracker.go
Labels: docs-not-required, release-note-required

#1230 Fix typos
  docs/data-model.md
  lib/apis/v3/felixconfig.go
  lib/backend/compat/compat.go
  lib/backend/etcd/syncer.go
  lib/backend/etcdv3/etcdv3.go
  lib/backend/k8s/k8s_test.go
  lib/backend/k8s/resources/networkpolicy.go
  lib/backend/k8s/resources/profile.go
  lib/backend/k8s/resources/resources.go
  lib/client/client_test.go
  lib/errors/errors.go
  lib/health/health.go
  lib/ipam/ipam_block_reader_writer.go
  lib/upgrade/migrator/clients/v1/compat/compat.go
  lib/upgrade/migrator/migrate.go
  lib/upgrade/migrator/migrate_test.go
Labels: docs-not-required, release-note-not-required

#1235 Simplify Kubernetes port lists to minimal ranges.
  lib/backend/k8s/conversion/conversion.go
  lib/backend/k8s/conversion/conversion_test.go
Labels: docs-not-required, release-note-required

#1239 Update default value comments for FailsafeInboundHostPorts and FailsafeOutboundHostPorts
  lib/apis/v3/felixconfig.go
Labels: docs-completed, release-note-not-required

#1240 Merge pull request #1239 from neiljerram/default-allow-port-6443
  lib/apis/v3/felixconfig.go
Labels: docs-completed, release-note-not-required

#1237 Automatically generate CRD yamls from code
  Makefile
  config/crd/crd.projectcalico.org_bgpconfigurations.yaml
  config/crd/crd.projectcalico.org_bgppeers.yaml
  config/crd/crd.projectcalico.org_blockaffinities.yaml
  config/crd/crd.projectcalico.org_clusterinformations.yaml
  config/crd/crd.projectcalico.org_felixconfigurations.yaml
  config/crd/crd.projectcalico.org_globalnetworkpolicies.yaml
  config/crd/crd.projectcalico.org_globalnetworksets.yaml
  config/crd/crd.projectcalico.org_hostendpoints.yaml
  config/crd/crd.projectcalico.org_ipamblocks.yaml
  config/crd/crd.projectcalico.org_ipamconfigs.yaml
  config/crd/crd.projectcalico.org_ipamhandles.yaml
  config/crd/crd.projectcalico.org_ippools.yaml
  config/crd/crd.projectcalico.org_kubecontrollersconfigurations.yaml
  config/crd/crd.projectcalico.org_networkpolicies.yaml
  config/crd/crd.projectcalico.org_networksets.yaml
  go.sum
  lib/apis/crd.projectcalico.org/v1/README.md
  lib/apis/crd.projectcalico.org/v1/bgpconfig_types.go
  lib/apis/crd.projectcalico.org/v1/bgppeer_types.go
  lib/apis/crd.projectcalico.org/v1/block_affinity_types.go
  lib/apis/crd.projectcalico.org/v1/clusterinformation_types.go
  lib/apis/crd.projectcalico.org/v1/doc.go
  lib/apis/crd.projectcalico.org/v1/felixconfiguration_types.go
  lib/apis/crd.projectcalico.org/v1/globalnetworkpolicy_types.go
  lib/apis/crd.projectcalico.org/v1/globalnetworkset_types.go
  lib/apis/crd.projectcalico.org/v1/hostendpoint_types.go
  lib/apis/crd.projectcalico.org/v1/ipamblock_types.go
  lib/apis/crd.projectcalico.org/v1/ipamconfig_types.go
  lib/apis/crd.projectcalico.org/v1/ipamhandle_types.go
  lib/apis/crd.projectcalico.org/v1/ippool_types.go
  lib/apis/crd.projectcalico.org/v1/kubecontrollersconfiguration_types.go
  lib/apis/crd.projectcalico.org/v1/networkpolicy_types.go
  lib/apis/crd.projectcalico.org/v1/networkset_types.go
  lib/apis/v3/clusterinfo.go
  lib/apis/v3/globalnetworkpolicy.go
  lib/apis/v3/ipam_block.go
  lib/apis/v3/kubecontrollersconfig.go
  lib/apis/v3/networkpolicy.go
  lib/backend/k8s/k8s_test.go
  lib/ipam/ipam_block_reader_writer_test.go
  lib/numorstring/port.go
  lib/numorstring/uint8orstring.go
  test/crds.yaml
Labels: docs-completed, release-note-required

#1238 FelixConfigurationSpec.BPFKubeProxyEndpointSlicesEnabled
  lib/apis/v3/felixconfig.go
  lib/apis/v3/zz_generated.deepcopy.go
  lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
Labels: docs-pr-required, release-note-required

#1242 Add tunnel ip allocator syncer, and add wireguard ipam allocation type
  .gitignore
  lib/backend/model/block.go
  lib/backend/syncersv1/tunnelipsyncer/doc.go
  lib/backend/syncersv1/tunnelipsyncer/tunnelipsyncer.go
  lib/backend/syncersv1/tunnelipsyncer/tunnelipsyncer_e2e_test.go
  lib/backend/syncersv1/tunnelipsyncer/tunnelipsyncer_suite_test.go
  lib/ipam/ipam.go
Labels: docs-pr-required, release-note-required
