Repository projectcalico/libcalico-go, pull requests merged in 2020-08, with the labels that each got.

#1277 Make bpfLogLevel an optional field
  config/crd/crd.projectcalico.org_felixconfigurations.yaml
  lib/apis/v3/felixconfig.go
Labels: docs-pr-required, release-note-required

#1276 Added Windows support and new API EnsureBlock to IPAM
  lib/ipam/interface.go
  lib/ipam/ipam.go
  lib/ipam/ipam_block.go
  lib/ipam/ipam_block_reader_writer.go
  lib/ipam/ipam_block_reader_writer_test.go
  lib/ipam/ipam_errors.go
  lib/ipam/ipam_test.go
  lib/ipam/ipam_types.go
  lib/ipam/ipam_win_test.go
Labels: docs-not-required, release-note-required

#1278 Properly fill status.podcidrs
  lib/backend/k8s/resources/node.go
Labels: docs-not-required, release-note-required

#1280 Validate IP and Port in PeerIP
  lib/validator/v3/validator.go
  lib/validator/v3/validator_test.go
Labels: docs-not-required, release-note-not-required

#1281 Remove whitelist terminology
  lib/apis/v3/bgpconfig.go
Labels: docs-not-required, release-note-not-required

#1282 And update CRDs
  config/crd/crd.projectcalico.org_bgpconfigurations.yaml
Labels: docs-not-required, release-note-not-required

#1283 Semaphore v2 migration
  .semaphore/semaphore.yml
Labels: docs-not-required, release-note-not-required

#1284 Handle deletion of weps in KDD
  lib/backend/k8s/conversion/constants.go
  lib/backend/k8s/conversion/conversion.go
  lib/backend/k8s/conversion/workload_endpoint_default.go
  lib/backend/k8s/k8s_test.go
  lib/backend/k8s/resources/errors.go
  lib/backend/k8s/resources/workloadendpoint.go
  lib/backend/k8s/resources/workloadendpoint_test.go
  lib/clientv3/resources.go
  lib/options/delete.go
Labels: cherry-pick-candidate, docs-not-required, release-note-required

#1285 Work around: Drop the resource version when patching pods to add IPs.
  lib/backend/k8s/k8s_test.go
  lib/backend/k8s/resources/workloadendpoint.go
Labels: docs-not-required, release-note-not-required

#1286 [v3.16] Backport bpf fixes
  lib/backend/k8s/conversion/constants.go
  lib/backend/k8s/conversion/conversion.go
  lib/backend/k8s/conversion/workload_endpoint_default.go
  lib/backend/k8s/k8s_test.go
  lib/backend/k8s/resources/errors.go
  lib/backend/k8s/resources/workloadendpoint.go
  lib/backend/k8s/resources/workloadendpoint_test.go
  lib/clientv3/resources.go
  lib/options/delete.go
Labels: docs-not-required, release-note-not-required

#1288 Ensure node processor returns a nil interface value for a delete
  lib/backend/syncersv1/updateprocessors/felixnodeprocessor.go
  lib/backend/syncersv1/updateprocessors/felixnodeprocessor_test.go
Labels: docs-not-required, release-note-required

#1289 Change Unicode apostrophe in API comments to ASCII apostrophe
  config/crd/crd.projectcalico.org_bgppeers.yaml
  config/crd/crd.projectcalico.org_felixconfigurations.yaml
  config/crd/crd.projectcalico.org_globalnetworkpolicies.yaml
  config/crd/crd.projectcalico.org_networkpolicies.yaml
  lib/apis/v3/bgppeer.go
  lib/apis/v3/felixconfig.go
  lib/apis/v3/hostendpoint.go
  lib/apis/v3/policy.go
  lib/backend/k8s/resources/workloadendpoint.go
Labels: docs-pr-required, release-note-required

#1291 [v3.16] Backport fix for nil Node resource
  lib/backend/syncersv1/updateprocessors/felixnodeprocessor.go
  lib/backend/syncersv1/updateprocessors/felixnodeprocessor_test.go
Labels: docs-not-required, release-note-required

#1290 [v3.15] Backport fix for nil Node resource
  lib/backend/syncersv1/updateprocessors/felixnodeprocessor.go
  lib/backend/syncersv1/updateprocessors/felixnodeprocessor_test.go
Labels: docs-pr-required, release-note-required
