Repository projectcalico/libcalico-go, pull requests merged in 2020-04, with the labels that each got.

#1209 Threadsafe creation of KDD clients
  lib/backend/k8s/k8s.go
Labels: docs-pr-required, release-note-required

#1210 Handle not-found errors in watchercache; revert to poll
  lib/backend/watchersyncer/watchercache.go
  lib/backend/watchersyncer/watchersyncer_test.go
Labels: docs-pr-required, release-note-required

#1214 Add inline kubecfg
  lib/apiconfig/apiconfig.go
  lib/backend/k8s/k8s.go
  lib/backend/k8s/k8s_test.go
Labels: docs-pr-required, release-note-required

#1216 Instead of creating inline k8s add a DatastoreDescribe
  lib/backend/k8s/k8s_test.go
  lib/testutils/e2e_describe.go
Labels: docs-not-required, release-note-not-required

#1217 Add an OrchRef in KDD node conversion
  lib/backend/k8s/resources/node.go
  lib/backend/k8s/resources/node_test.go
Labels: docs-not-required, release-note-not-required

#1218 Automated cherry pick of #1217: Add an OrchRef in KDD node conversion
  lib/backend/k8s/resources/node.go
  lib/backend/k8s/resources/node_test.go
Labels: docs-not-required, release-note-not-required

#1208 Refactor WorkloadEndpoint conversion and clients
  lib/backend/k8s/conversion/conversion.go
  lib/backend/k8s/conversion/conversion_test.go
  lib/backend/k8s/conversion/workload_endpoint.go
  lib/backend/k8s/conversion/workload_endpoint_default.go
  lib/backend/k8s/resources/networkpolicy.go
  lib/backend/k8s/resources/profile.go
  lib/backend/k8s/resources/resources.go
  lib/backend/k8s/resources/resources_test.go
  lib/backend/k8s/resources/watcher.go
  lib/backend/k8s/resources/workloadendpoint.go
  lib/backend/k8s/resources/workloadendpoint_test.go
  lib/backend/syncersv1/updateprocessors/networkpolicyprocessor_test.go
  lib/clientv3/networkpolicy_e2e_test.go
Labels: docs-not-required, release-note-not-required

#1221 Add BPFDisableUnprivileged config param.
  go.sum
  lib/apis/v3/felixconfig.go
  lib/apis/v3/zz_generated.deepcopy.go
  lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
Labels: docs-pr-required, release-note-required

#1222 Add FelixConfiguration for route source
  lib/apis/v3/felixconfig.go
  lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  lib/validator/v3/validator.go
Labels: docs-pr-required, release-note-required

#1212 Stream the whole v3 Profile resource as well as legacy v1 pieces
  lib/backend/model/keys.go
  lib/backend/syncersv1/felixsyncer/felixsyncer_e2e_test.go
  lib/backend/syncersv1/updateprocessors/profileprocessor.go
  lib/backend/syncersv1/updateprocessors/profileprocessor_test.go
Labels: docs-not-required, release-note-not-required

#1211 Refactor selector expression building
  lib/backend/syncersv1/updateprocessors/rules.go
Labels: docs-not-required, release-note-not-required

#1207 Add an allow-all profile
  lib/backend/etcdv3/etcdv3.go
  lib/backend/etcdv3/watcher.go
  lib/backend/k8s/conversion/conversion.go
  lib/backend/k8s/k8s_test.go
  lib/backend/k8s/resources/profile.go
  lib/backend/syncersv1/felixsyncer/felixsyncer_e2e_test.go
  lib/clientv3/profile.go
  lib/clientv3/profile_e2e_test.go
  lib/resources/static.go
Labels: docs-pr-required, release-note-required

#1224 update go-yaml
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#1225 Fix felix syncer e2e
  lib/backend/syncersv1/felixsyncer/felixsyncer_e2e_test.go
Labels: docs-not-required, release-note-not-required

#1227 Don't rewrite the v3 policy protocol when converting it to v1
  lib/backend/syncersv1/updateprocessors/rules.go
  lib/backend/syncersv1/updateprocessors/rules_test.go
  lib/backend/syncersv1/updateprocessors/shared_test.go
Labels: docs-not-required, release-note-not-required

#1226 Felix config field for range of route tables to use
  lib/apis/v3/felixconfig.go
  lib/apis/v3/zz_generated.deepcopy.go
  lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  lib/backend/syncersv1/updateprocessors/felixconfigprocessor.go
  lib/validator/v3/validator.go
  lib/validator/v3/validator_test.go
Labels: docs-pr-required, release-note-not-required

#1228 Don't mask the newBlock function
  lib/ipam/ipam.go
Labels: docs-not-required, release-note-not-required

#1219 Add GlobalNetworkPolicy short name
  test/crds.yaml
Labels: docs-not-required, release-note-not-required

#1220 IPAM StrictAffinity: support to configure it.
  lib/backend/k8s/resources/ipam_block.go
  lib/backend/model/block.go
  lib/backend/syncersv1/felixsyncer/felixsyncer_e2e_test.go
  lib/ipam/ipam.go
  lib/ipam/ipam_block.go
  lib/ipam/ipam_block_reader_writer.go
  lib/ipam/ipam_block_reader_writer_test.go
  lib/ipam/ipam_test.go
Labels: docs-not-required, release-note-not-required

#1215 Wireguard configuration in FelixConfig and Node v3 resources.
  go.mod
  go.sum
  lib/apis/v3/felixconfig.go
  lib/apis/v3/node.go
  lib/apis/v3/zz_generated.deepcopy.go
  lib/backend/k8s/resources/node.go
  lib/backend/model/keys.go
  lib/backend/model/node.go
  lib/backend/syncersv1/felixsyncer/felixsyncer_e2e_test.go
  lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  lib/backend/syncersv1/updateprocessors/felixnodeprocessor.go
  lib/backend/syncersv1/updateprocessors/felixnodeprocessor_test.go
  lib/clientv3/node_e2e_test.go
  lib/validator/v3/validator.go
  lib/validator/v3/validator_test.go
Labels: docs-pr-required, release-note-required
