Repository projectcalico/libcalico-go, pull requests merged in 2020-03, with the labels that each got.

#1196 Return handle with assignment attributes
  lib/ipam/interface.go
  lib/ipam/ipam.go
  lib/ipam/ipam_block.go
  lib/ipam/ipam_test.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#1197 add goreportcard to README
  README.md
Labels: docs-not-required, release-note-not-required

#1199 Return a typed error if IP already allocated
  lib/ipam/ipam_block.go
  lib/ipam/ipam_test.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#1200 Automated cherry pick of #1196: Return handle with assignment attributes
  lib/ipam/interface.go
  lib/ipam/ipam.go
  lib/ipam/ipam_block.go
  lib/ipam/ipam_test.go
Labels: docs-not-required, release-note-required

#1201 Automated cherry pick of #1196: Return handle with assignment attributes
  lib/ipam/interface.go
  lib/ipam/ipam.go
  lib/ipam/ipam_block.go
  lib/ipam/ipam_test.go
Labels: docs-not-required, release-note-not-required

#1204 Add optional component to log format
  lib/logutils/logutils.go
Labels: docs-not-required, release-note-not-required

#1203 KubeControllersConfiguration v3 API object
  lib/apis/v3/felixconfig.go
  lib/apis/v3/kubecontrollersconfig.go
  lib/apis/v3/zz_generated.deepcopy.go
  lib/clientv3/felixconfig.go
  lib/validator/v3/validator.go
  lib/validator/v3/validator_test.go
Labels: docs-pr-required, release-note-required

#1205 v3 Client support for KubeControllersConfiguration
  lib/apis/v3/constants.go
  lib/backend/k8s/k8s.go
  lib/backend/k8s/resources/kubecontrollersconfig.go
  lib/backend/model/resource.go
  lib/clientv3/client.go
  lib/clientv3/common_test.go
  lib/clientv3/interface.go
  lib/clientv3/kubecontrollersconfig.go
  lib/clientv3/kubecontrollersconfig_e2e_test.go
  lib/testutils/resources.go
  test/crds.yaml
Labels: docs-pr-required, release-note-required

#1206 KubeControllersConfig uses metav1.Duration
  lib/apis/v3/kubecontrollersconfig.go
  lib/apis/v3/zz_generated.deepcopy.go
  lib/clientv3/kubecontrollersconfig_e2e_test.go
  lib/validator/v3/validator.go
  lib/validator/v3/validator_test.go
Labels: docs-not-required, release-note-not-required
