Repository projectcalico/libcalico-go, pull requests merged in 2021-04, with the labels that each got.

#1357 Add support for Kubernetes EndPort field
  go.mod
  go.sum
  lib/apis/v1/openapi_generated.go
  lib/apis/v3/openapi_generated.go
  lib/backend/k8s/conversion/conversion.go
  lib/backend/k8s/conversion/conversion_test.go
  lib/numorstring/openapi_generated.go
Labels: docs-not-required, release-note-required

#1397 Fix handling of empty podIPs annotation
  lib/backend/k8s/conversion/conversion.go
  lib/backend/k8s/conversion/conversion_test.go
Labels: docs-not-required, release-note-required

#1399 Fix that SCTP named ports were not copied from Pod to WorkloadEndpoint.
  lib/backend/k8s/conversion/conversion_test.go
  lib/backend/k8s/conversion/workload_endpoint_default.go
Labels: docs-not-required, release-note-required

#1401 Automated cherry pick of #1363: Fix libcalico returning a generic kubernetes error
  lib/backend/k8s/resources/workloadendpoint.go
Labels: docs-not-required, release-note-required

#1400 Move FindNodeAddresses API to node object
  lib/backend/syncersv1/updateprocessors/felixnodeprocessor.go
  lib/resources/node.go
Labels: docs-not-required, release-note-not-required

#1398 Split calico / k8s NP
  go.mod
  go.sum
  lib/backend/k8s/conversion/conversion.go
  lib/backend/k8s/conversion/conversion_test.go
  lib/backend/k8s/k8s.go
  lib/backend/k8s/k8s_test.go
  lib/backend/k8s/resources/customresource.go
  lib/backend/k8s/resources/kubenetworkpolicy.go
  lib/backend/k8s/resources/networkpolicy.go
  lib/backend/model/kubenetworkpolicy.go
  lib/backend/model/resource.go
  lib/backend/syncersv1/felixsyncer/felixsyncerv1.go
  lib/clientv3/networkpolicy_e2e_test.go
  lib/namespace/resource.go
Labels: docs-pr-required, release-note-required

#1403 Bump build version and add organization env / format fixes
  Makefile
  lib/apis/v3/zz_generated.deepcopy.go
  lib/backend/syncersv1/updateprocessors/felixnodeprocessor.go
Labels: docs-not-required, merge-when-ready, release-note-not-required

#1405 Add IPv6 network support for failsafe rules
  config/crd/crd.projectcalico.org_felixconfigurations.yaml
  lib/apis/v3/felixconfig.go
  lib/backend/syncersv1/updateprocessors/felixconfigprocessor.go
  lib/upgrade/migrator/felixconfig.go
Labels: docs-not-required, release-note-not-required

#1404 Add BPFExtToServiceConnmark Felix config option
  config/crd/crd.projectcalico.org_felixconfigurations.yaml
  docs/boilerplate.go.txt
  lib/apis/v1/openapi_generated.go
  lib/apis/v3/felixconfig.go
  lib/apis/v3/openapi_generated.go
  lib/apis/v3/zz_generated.deepcopy.go
  lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  lib/numorstring/openapi_generated.go
  lib/upgrade/migrator/clients/v1/k8s/custom/zz_generated.deepcopy.go
  lib/validator/v3/validator_test.go
Labels: docs-pr-required, release-note-required

#1406 Revert "Fix handling of empty podIPs annotation"
  lib/backend/k8s/conversion/conversion.go
  lib/backend/k8s/conversion/conversion_test.go
Labels: docs-pr-required, release-note-required

#1369 ippool Spec.CIDR support ipv6 full representation, ipv4 with host bit set
  lib/ipam/ipam.go
  lib/ipam/ipam_test.go
Labels: docs-not-required, merge-when-ready, release-note-required

#1407 Revert "Automated cherry pick of #1397: Fix handling of empty podIPs annotation"
  lib/backend/k8s/conversion/conversion.go
  lib/backend/k8s/conversion/conversion_test.go
Labels: docs-not-required, merge-when-ready, release-note-not-required

#1408 Failsafe ipv6 3.17
  config/crd/crd.projectcalico.org_felixconfigurations.yaml
  go.mod
  lib/apis/v3/felixconfig.go
  lib/apis/v3/openapi_generated.go
  lib/backend/syncersv1/updateprocessors/felixconfigprocessor.go
  lib/numorstring/openapi_generated.go
  lib/upgrade/migrator/felixconfig.go
Labels: docs-not-required, release-note-not-required

#1409 Failsafe ipv6 3.18
  config/crd/crd.projectcalico.org_felixconfigurations.yaml
  go.mod
  lib/apis/v3/felixconfig.go
  lib/apis/v3/openapi_generated.go
  lib/backend/syncersv1/updateprocessors/felixconfigprocessor.go
  lib/numorstring/openapi_generated.go
  lib/upgrade/migrator/felixconfig.go
Labels: docs-not-required, release-note-not-required

#1411 Revert updates to openapi
  go.mod
  lib/apis/v3/openapi_generated.go
  lib/numorstring/openapi_generated.go
Labels: docs-not-required, release-note-not-required

#1410 Revert updates to openapi
  go.mod
  lib/apis/v3/openapi_generated.go
  lib/numorstring/openapi_generated.go
Labels: docs-not-required, release-note-not-required

#1412 Bm trigger apiserver pin updates
  Makefile
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1413 Trigger app policy pin update
  Makefile
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required
