Repository projectcalico/libcalico-go, pull requests merged in 2021-10, with the labels that each got.

#1510 Add release Makefile targets
  Makefile
Labels: docs-not-required, release-note-not-required

#1508 [allowed-use] Introduce support for allowed uses of IPAM pools.
  config/crd/crd.projectcalico.org_ippools.yaml
  go.mod
  go.sum
  lib/backend/model/ippool.go
  lib/backend/syncersv1/bgpsyncer/bgpsyncer_e2e_test.go
  lib/backend/syncersv1/updateprocessors/ippoolprocessor_test.go
  lib/clientv3/common_test.go
  lib/clientv3/ippool.go
  lib/clientv3/ippool_e2e_test.go
  lib/clientv3/ippool_kdd_conversion_test.go
  lib/ipam/ipam.go
  lib/ipam/ipam_block_reader_writer.go
  lib/ipam/ipam_block_reader_writer_test.go
  lib/ipam/ipam_test.go
  lib/ipam/ipam_types.go
  lib/ipam/ipam_win_test.go
  lib/upgrade/converters/ippool.go
  lib/upgrade/converters/ippool_test.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#1509 [ip-reservations] Implement IP reservations
  config/crd/crd.projectcalico.org_ipreservations.yaml
  go.mod
  go.sum
  lib/apis/crd.projectcalico.org/v1/ipreservation_types.go
  lib/backend/k8s/k8s.go
  lib/backend/k8s/resources/customresource.go
  lib/backend/k8s/resources/ipreservation.go
  lib/backend/model/block.go
  lib/backend/model/resource.go
  lib/clientv3/client.go
  lib/clientv3/interface.go
  lib/clientv3/ipreservation.go
  lib/ipam/addr_filter.go
  lib/ipam/addr_filter_test.go
  lib/ipam/ipam.go
  lib/ipam/ipam_block.go
  lib/ipam/ipam_block_reader_writer.go
  lib/ipam/ipam_block_reader_writer_test.go
  lib/ipam/ipam_test.go
  lib/ipam/ipam_win_test.go
  lib/net/ip.go
  lib/net/ipnet.go
  lib/net/ipnet_test.go
  lib/validator/v3/validator.go
  lib/validator/v3/validator_test.go
Labels: release-note-required, docs-pr-required, merge-when-ready

#1504 Use v1 EndpointSlice API
  Makefile
  go.mod
  go.sum
  lib/apis/v1/openapi_generated.go
  lib/apis/v3/openapi_generated.go
  lib/backend/k8s/conversion/conversion.go
  lib/backend/k8s/resources/kubeendpointslice.go
  lib/backend/model/resource.go
  lib/backend/syncersv1/felixsyncer/felixsyncer_e2e_test.go
Labels: release-note-required, docs-not-required

#1511 Add simple first and interval logger
  lib/logutils/logutils.go
  lib/logutils/ratelimitedlogger.go
  lib/logutils/ratelimitedlogger_test.go
Labels: release-note-required, docs-pr-required

#1520 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1522 Revert to v1beta1 endpoint slices
  lib/backend/k8s/conversion/conversion.go
  lib/backend/k8s/resources/kubeendpointslice.go
  lib/backend/model/resource.go
  lib/backend/syncersv1/felixsyncer/felixsyncer_e2e_test.go
Labels: docs-not-required, release-note-not-required

#1524 bpfSNATPorts option
  config/crd/crd.projectcalico.org_felixconfigurations.yaml
Labels: release-note-required, docs-pr-required

#1529 Ensure we check CRDs if they are up to date
  Makefile
  config/crd/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-not-required, release-note-not-required
