Repository projectcalico/libcalico-go, pull requests merged in 2021-08, with the labels that each got.

#1480 Update syncer test framework to have better kvp comparison and defaulted filtering of updates
  Makefile
  lib/backend/k8s/k8s_test.go
  lib/backend/syncersv1/felixsyncer/felixsyncer_e2e_test.go
  lib/ipam/ipam_test.go
  lib/testutils/delete.go
  lib/testutils/syncertester.go
Labels: release-note-required, docs-pr-required

#1489 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1488 Close race condition when allocating new block
  lib/ipam/ipam.go
  lib/ipam/ipam_block_reader_writer.go
Labels: release-note-required, docs-not-required, merge-when-ready

#1490 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1492 Update go-build version to v0.55, with pinned generation tools
  Makefile
Labels: release-note-required, docs-pr-required

#1494 Add note regarding official API
  README.md
Labels: release-note-required, docs-pr-required

#1471 Add HostPort support
  lib/apis/v3/openapi_generated.go
  lib/apis/v3/workloadendpoint.go
  lib/apis/v3/zz_generated.deepcopy.go
  lib/backend/k8s/conversion/conversion_test.go
  lib/backend/k8s/conversion/workload_endpoint_default.go
  lib/backend/syncersv1/updateprocessors/workloadendpointprocessor_test.go
  lib/clientv3/workloadendpoint_e2e_test.go
  lib/upgrade/converters/workloadendpoint.go
  lib/upgrade/converters/workloadendpoint_test.go
  lib/validator/v3/validator.go
  lib/validator/v3/validator_test.go
Labels: release-note-required, docs-pr-required
