Repository projectcalico/libcalico-go, pull requests merged in 2021-09, with the labels that each got.

#1484 List / Watch optimizations
  lib/backend/k8s/k8s.go
  lib/backend/k8s/k8s_test.go
  lib/backend/k8s/resources/customresource.go
  lib/backend/k8s/resources/ipam_block.go
  lib/backend/k8s/resources/kubeendpointslice.go
  lib/backend/k8s/resources/kubenetworkpolicy.go
  lib/backend/k8s/resources/list_pager.go
  lib/backend/k8s/resources/node.go
  lib/backend/k8s/resources/profile.go
  lib/backend/k8s/resources/workloadendpoint.go
  lib/backend/watchersyncer/watchercache.go
Labels: release-note-required, docs-pr-required

#1497 Assert generated files don't change as part of CI
  Makefile
  config/crd/crd.projectcalico.org_bgppeers.yaml
  config/crd/crd.projectcalico.org_felixconfigurations.yaml
  lib/backend/k8s/resources/list_pager.go
Labels: release-note-required, docs-pr-required

#1499 Update openapi and generate files
  go.mod
  go.sum
  lib/apis/v1/openapi_generated.go
  lib/apis/v3/openapi_generated.go
Labels: release-note-required, docs-pr-required

#1496 Use Info log level on allocation performance measurement tests
  lib/ipam/ipam_test.go
Labels: docs-not-required, release-note-not-required

#1501 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1500 Fix openapi generated files
  go.mod
  go.sum
  lib/apis/v1/openapi_generated.go
  lib/apis/v3/openapi_generated.go
Labels: docs-not-required, release-note-not-required

#1503 bpfSNATPorts option
  config/crd/crd.projectcalico.org_felixconfigurations.yaml
Labels: release-note-required, docs-pr-required

#1505 Update generated files
  config/crd/crd.projectcalico.org_felixconfigurations.yaml
Labels: release-note-required, docs-pr-required

#1495 Upgrade etcd to 3.5.0
  go.mod
  go.sum
  lib/backend/etcd/etcd.go
  lib/backend/etcdv3/conversion.go
  lib/backend/etcdv3/etcdv3.go
  lib/backend/etcdv3/watcher.go
Labels: release-note-required, docs-not-required

#1506 Revert "Upgrade etcd to 3.5.0 (#1495)"
  go.mod
  go.sum
  lib/backend/etcd/etcd.go
  lib/backend/etcdv3/conversion.go
  lib/backend/etcdv3/etcdv3.go
  lib/backend/etcdv3/watcher.go
Labels: release-note-required, docs-pr-required
