Repository projectcalico/libcalico-go, pull requests merged in 2021-02, with the labels that each got.

#1362 Add config for prometheus metrics port for kube-controllers
  config/crd/crd.projectcalico.org_kubecontrollersconfigurations.yaml
  lib/apis/v3/kubecontrollersconfig.go
  lib/apis/v3/zz_generated.deepcopy.go
  lib/clientv3/kubecontrollersconfig.go
  lib/clientv3/kubecontrollersconfig_e2e_test.go
Labels: docs-pr-required, release-note-required

#1361 Support multiple kubeconfig files via env var 'KUBECONFIG'
  lib/backend/k8s/k8s.go
  lib/backend/k8s/k8s_client_test.go
Labels: docs-pr-required, merge-when-ready, release-note-required

#1364 Speed up releasing of many IPs at once by doing each block in parallel
  go.mod
  go.sum
  lib/ipam/ipam.go
  lib/ipam/ipam_block_reader_writer.go
Labels: docs-not-required, release-note-not-required

#1365 Automated cherry pick of #1364: Speed up releasing of many IPs at once by doing each
  go.mod
  go.sum
  lib/ipam/ipam.go
  lib/ipam/ipam_block_reader_writer.go
Labels: docs-not-required, release-note-not-required

#1366 Fix release deadlock
  lib/ipam/ipam.go
  lib/ipam/ipam_test.go
Labels: docs-not-required, release-note-not-required

#1367 Automated cherry pick of #1366: Fix release deadlock
  lib/ipam/ipam.go
  lib/ipam/ipam_test.go
Labels: docs-not-required, release-note-not-required

#1368 Add a default max blocks per host
  lib/ipam/ipam.go
  lib/ipam/ipam_test.go
Labels: docs-not-required, release-note-required
