Repository projectcalico/libcalico-go, pull requests merged in 2021-07, with the labels that each got.

#1444 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1436 Improve IPAM logging info returned by AutoAssign()
  lib/backend/syncersv1/bgpsyncer/bgpsyncer_e2e_test.go
  lib/clientv3/ippool_e2e_test.go
  lib/ipam/interface.go
  lib/ipam/ipam.go
  lib/ipam/ipam_block_reader_writer_test.go
  lib/ipam/ipam_test.go
  lib/ipam/ipam_win_test.go
Labels: docs-not-required, release-note-required

#1445 Add MaxRestartTime testing (for BGP graceful restart timer)
  lib/validator/v3/validator_test.go
Labels: docs-pr-required, release-note-required

#1446 Fix checking terminating pod for non-calico CNI
  lib/backend/k8s/conversion/conversion.go
  lib/backend/k8s/conversion/conversion_test.go
Labels: docs-pr-required, release-note-required

#1447 Merge pull request #1446 from song-jiang/song-fix-pod-termination
  lib/backend/k8s/conversion/conversion.go
  lib/backend/k8s/conversion/conversion_test.go
Labels: docs-not-required, release-note-required

#1449 Merge pull request #1447 from song-jiang/song-pick-v3.19
  lib/backend/k8s/conversion/conversion.go
  lib/backend/k8s/conversion/conversion_test.go
Labels: docs-pr-required, release-note-required

#1450 Merge pull request #1447 from song-jiang/song-pick-v3.19
  lib/backend/k8s/conversion/conversion.go
  lib/backend/k8s/conversion/conversion_test.go
Labels: docs-pr-required, release-note-required

#1451 Merge pull request #1447 from song-jiang/song-pick-v3.19
  lib/backend/k8s/conversion/conversion.go
  lib/backend/k8s/conversion/conversion_test.go
Labels: docs-pr-required, release-note-required

#1452 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
  lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
Labels: docs-not-required, release-note-not-required

#1453 Fix pin updates for CNI plugin
  Makefile
Labels: docs-not-required, release-note-not-required

#1454 Fix pin updates for multiple repos
  Makefile
Labels: docs-not-required, release-note-not-required

#1455 Fix pin updates for CNI plugin
  Makefile
Labels: docs-not-required, release-note-not-required

#1456 Fix pin updates for CNI plugin
  Makefile
Labels: docs-not-required, release-note-not-required

#1457 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1459 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1460 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1461 Add missing maxRestartTime to BGP peers CRD
  config/crd/crd.projectcalico.org_bgppeers.yaml
Labels: docs-pr-required, release-note-required

#1458 Simplify processing of v3 resources
  lib/backend/model/keys.go
  lib/backend/model/keys_test.go
  lib/backend/model/resource.go
Labels: docs-pr-required, release-note-required

#1463 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1462 Add missing maxRestartTime to BGP peer CRD (cherry pick to v3.20)
  config/crd/crd.projectcalico.org_bgppeers.yaml
Labels: docs-not-required, release-note-not-required

#1466 Update projectcalico/api pin
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#1443 Add EndpointSlice and new policy fields to syncer
  config/crd/crd.projectcalico.org_felixconfigurations.yaml
  config/crd/crd.projectcalico.org_globalnetworkpolicies.yaml
  config/crd/crd.projectcalico.org_networkpolicies.yaml
  go.sum
  lib/backend/k8s/conversion/conversion.go
  lib/backend/k8s/k8s.go
  lib/backend/k8s/resources/kubeendpointslice.go
  lib/backend/model/keys.go
  lib/backend/model/kubeendpointslice.go
  lib/backend/model/resource.go
  lib/backend/model/rule.go
  lib/backend/syncersv1/felixsyncer/felixsyncer_e2e_test.go
  lib/backend/syncersv1/felixsyncer/felixsyncerv1.go
  lib/backend/syncersv1/updateprocessors/rules.go
  lib/backend/syncersv1/updateprocessors/rules_test.go
  lib/validator/v3/validator.go
  lib/validator/v3/validator_test.go
Labels: docs-pr-required, release-note-required

#1467 Override OpenAPI definition for Port, Protocol and Uint8OrString
  lib/apis/v1/openapi_generated.go
  lib/apis/v3/openapi_generated.go
  lib/numorstring/openapi_generated.go
  lib/numorstring/port.go
  lib/numorstring/protocol.go
  lib/numorstring/uint8orstring.go
Labels: docs-not-required, release-note-not-required

#1468 Automated cherry pick of #1443: Add EndpointSlices and new service policy rules to syncer
  config/crd/crd.projectcalico.org_felixconfigurations.yaml
  config/crd/crd.projectcalico.org_globalnetworkpolicies.yaml
  config/crd/crd.projectcalico.org_networkpolicies.yaml
  go.sum
  lib/backend/k8s/conversion/conversion.go
  lib/backend/k8s/k8s.go
  lib/backend/k8s/resources/kubeendpointslice.go
  lib/backend/model/keys.go
  lib/backend/model/kubeendpointslice.go
  lib/backend/model/resource.go
  lib/backend/model/rule.go
  lib/backend/syncersv1/felixsyncer/felixsyncer_e2e_test.go
  lib/backend/syncersv1/felixsyncer/felixsyncerv1.go
  lib/backend/syncersv1/updateprocessors/rules.go
  lib/backend/syncersv1/updateprocessors/rules_test.go
  lib/validator/v3/validator.go
  lib/validator/v3/validator_test.go
Labels: docs-pr-required, release-note-required

#1469 Fix version of discovery API
  lib/backend/model/resource.go
Labels: docs-pr-required, release-note-required

#1470 Automated cherry pick of #1469: Fix version of discovery API
  lib/backend/model/resource.go
Labels: docs-pr-required, release-note-required

#1472 Add round tripping of ContainerID to KDD.
  lib/backend/k8s/conversion/constants.go
  lib/backend/k8s/conversion/workload_endpoint_default.go
  lib/backend/k8s/resources/workloadendpoint.go
  lib/backend/k8s/resources/workloadendpoint_test.go
Labels: docs-pr-required, release-note-required

#1475 Automated cherry pick of #1474: Fix bad validation on ServiceMatch
  lib/validator/v3/validator.go
  lib/validator/v3/validator_test.go
Labels: docs-not-required, release-note-not-required

#1474 Fix bad validation on ServiceMatch
  lib/validator/v3/validator.go
  lib/validator/v3/validator_test.go
Labels: docs-not-required, release-note-not-required

#1476 Fix handling of endpoint slices
  lib/backend/k8s/conversion/conversion.go
  lib/backend/model/resource.go
  lib/namespace/resource.go
Labels: docs-pr-required, release-note-required

#1478 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1479 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1477 Automated cherry pick of #1476: Fix handling of endpoint slices as namespaced resource
  lib/backend/k8s/conversion/conversion.go
  lib/backend/model/resource.go
  lib/namespace/resource.go
Labels: docs-not-required, release-note-not-required

#1481 [v3.20] Add round tripping of ContainerID to KDD.
  lib/backend/k8s/conversion/constants.go
  lib/backend/k8s/conversion/workload_endpoint_default.go
  lib/backend/k8s/resources/workloadendpoint.go
  lib/backend/k8s/resources/workloadendpoint_test.go
Labels: docs-not-required, release-note-required

#1482 [v3.19] Add round tripping of ContainerID to KDD.
  lib/backend/k8s/conversion/constants.go
  lib/backend/k8s/conversion/workload_endpoint_default.go
  lib/backend/k8s/resources/workloadendpoint.go
  lib/backend/k8s/resources/workloadendpoint_test.go
Labels: docs-pr-required, release-note-required

#1483 [v3.18] backport container ID
  lib/backend/k8s/conversion/constants.go
  lib/backend/k8s/conversion/workload_endpoint_default.go
  lib/backend/k8s/resources/workloadendpoint.go
  lib/backend/k8s/resources/workloadendpoint_test.go
Labels: docs-pr-required, release-note-required
