Repository projectcalico/libcalico-go, pull requests merged in 2021-05, with the labels that each got.

#1417 Make the failsafe cidr optional
  config/crd/crd.projectcalico.org_felixconfigurations.yaml
  lib/apis/v3/felixconfig.go
Labels: docs-not-required, release-note-not-required

#1418 Make the failsafe cidr optional
  config/crd/crd.projectcalico.org_felixconfigurations.yaml
  lib/apis/v3/felixconfig.go
Labels: docs-not-required, release-note-not-required

#1419 Make the failsafe cidr optional
  config/crd/crd.projectcalico.org_felixconfigurations.yaml
  lib/apis/v3/felixconfig.go
Labels: docs-not-required, release-note-not-required

#1420 Make the failsafe cidr optional
  config/crd/crd.projectcalico.org_felixconfigurations.yaml
  lib/apis/v3/felixconfig.go
  lib/apis/v3/openapi_generated.go
Labels: docs-not-required, release-note-not-required

#1422 Use a spec field on WEPs for ServiceAccount name
  lib/apis/v3/openapi_generated.go
  lib/apis/v3/workloadendpoint.go
  lib/backend/k8s/conversion/conversion_test.go
  lib/backend/k8s/conversion/workload_endpoint_default.go
  lib/backend/syncersv1/updateprocessors/networkpolicyprocessor_test.go
  lib/backend/syncersv1/updateprocessors/workloadendpointprocessor.go
  lib/backend/syncersv1/updateprocessors/workloadendpointprocessor_test.go
Labels: docs-not-required, release-note-required

#1423 Automated cherry pick of #1422: Use a spec field on WEPs for ServiceAccount name
  lib/apis/v3/openapi_generated.go
  lib/apis/v3/workloadendpoint.go
  lib/backend/k8s/conversion/conversion_test.go
  lib/backend/k8s/conversion/workload_endpoint_default.go
  lib/backend/syncersv1/updateprocessors/networkpolicyprocessor_test.go
  lib/backend/syncersv1/updateprocessors/workloadendpointprocessor.go
  lib/backend/syncersv1/updateprocessors/workloadendpointprocessor_test.go
Labels: docs-not-required, release-note-required

#1425 Fix gen-files target to properly format generated files
  Makefile
Labels: docs-not-required, release-note-not-required

#1427 Remove dependence on unmaintained satori UUID library.
  go.mod
  go.sum
  lib/backend/k8s/resources/workloadendpoint_test.go
  lib/backend/watchersyncer/watchersyncer_test.go
  lib/client/workloadendpoint.go
  lib/clientv3/client.go
  lib/hwm/hwm.go
Labels: docs-pr-required, merge-when-ready, release-note-required
