Repository projectcalico/libcalico-go, pull requests merged in 2021-06, with the labels that each got.

#1431 Fix crd.projectcalico.org scheme
  lib/apis/v3/register.go
Labels: docs-not-required, release-note-not-required

#1429 Add grace period config for kube-controllers IPAM GC
  config/crd/crd.projectcalico.org_kubecontrollersconfigurations.yaml
  lib/apis/v3/kubecontrollersconfig.go
  lib/apis/v3/openapi_generated.go
  lib/apis/v3/zz_generated.deepcopy.go
  lib/clientv3/kubecontrollersconfig.go
Labels: docs-pr-required, release-note-required

#1433 Drop verbosity on spammy log
  lib/ipam/ipam.go
Labels: docs-pr-required, release-note-required

#1434 Fix sem timeouts and priorities
  .semaphore/semaphore.yml
Labels: docs-pr-required, release-note-required

#1435 Update to use kind for tests
  .gitignore
  Makefile
  go.mod
  go.sum
  lib/backend/k8s/k8s_test.go
  lib/backend/syncersv1/bgpsyncer/bgpsyncer_e2e_test.go
  lib/backend/syncersv1/felixsyncer/felixsyncer_e2e_test.go
  lib/testutils/e2e_describe.go
  test/kind-config.yaml
  test/mock-node.yaml
Labels: docs-not-required, release-note-not-required

#1438 Update api pins / allow api project to trigger pin update
  .semaphore/update_pins.yml
  Makefile
  go.mod
  test/dummy.go
Labels: delete-branch, docs-pr-required, merge-when-ready, release-note-required

#1439 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1441 bump number of tested flags 93 -> 94
  go.mod
  go.sum
  lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
Labels: docs-pr-required, release-note-required
