Repository projectcalico/libcalico-go, pull requests merged in 2021-11, with the labels that each got.

#1540 Add missing validation for allowedUses field.
  lib/validator/v3/validator.go
  lib/validator/v3/validator_test.go
Labels: release-note-required, docs-pr-required

#1541 Add missing validation for allowedUses field.
  lib/validator/v3/validator.go
  lib/validator/v3/validator_test.go
Labels: release-note-required, docs-pr-required

#1539 Update IP Pool CRD to contain disableBGPExport
  config/crd/crd.projectcalico.org_ippools.yaml
  go.mod
  go.sum
  lib/backend/model/ippool.go
  lib/backend/syncersv1/updateprocessors/ippoolprocessor.go
  lib/backend/syncersv1/updateprocessors/ippoolprocessor_test.go
  lib/clientv3/ippool_e2e_test.go
Labels: docs-not-required, release-note-not-required

#1543 [release-v3.21] Auto pick #1539: Update IP Pool CRD to contain disableBGPExport
  config/crd/crd.projectcalico.org_ippools.yaml
  go.mod
  go.sum
  lib/backend/model/ippool.go
  lib/backend/syncersv1/updateprocessors/ippoolprocessor.go
  lib/backend/syncersv1/updateprocessors/ippoolprocessor_test.go
  lib/clientv3/ippool_e2e_test.go
Labels: docs-not-required, release-note-not-required

#1544 Fix that Pod ports without a name were being sent to Felix
  lib/backend/syncersv1/updateprocessors/workloadendpointprocessor.go
  lib/validator/v3/validator_test.go
Labels: release-note-required, docs-not-required

#1545 Automated cherry pick of #1544: Fix that Pod ports without a name were being sent to Felix
  lib/backend/syncersv1/updateprocessors/workloadendpointprocessor.go
  lib/validator/v3/validator_test.go
Labels: release-note-required, docs-not-required

#1546 Add context to pod IP logs
  lib/backend/k8s/conversion/conversion.go
Labels: release-note-required, docs-pr-required

#1547 Update github.com/tchap/go-patricia/v2/patricia import
  go.mod
  go.sum
  lib/hwm/hwm.go
Labels: docs-not-required, release-note-not-required

#1548 Update github.com/tchap/go-patricia/v2/patricia import
  go.mod
  go.sum
  lib/hwm/hwm.go
Labels: docs-not-required, release-note-not-required
