Repository projectcalico/libcalico-go, pull requests merged in 2021-03, with the labels that each got.

#1370 Calico-4373: default missing protocol to TCP; don't let single port overwrite all ports
  lib/backend/k8s/conversion/conversion.go
  lib/backend/k8s/conversion/conversion_test.go
Labels: docs-not-required, release-note-required

#1371 [cherry-pick] Calico-4373: default missing protocol to TCP; don't let single port overwrite all ports
  lib/backend/k8s/conversion/conversion.go
  lib/backend/k8s/conversion/conversion_test.go
Labels: docs-not-required, release-note-required

#1372 [cherry-pick] Calico-4373: default missing protocol to TCP; don't let single port overwrite all ports
  lib/backend/k8s/conversion/conversion.go
  lib/backend/k8s/conversion/conversion_test.go
Labels: docs-not-required, release-note-required

#1373 [cherry-pick] Calico-4373: default missing protocol to TCP; don't let single port overwrite all ports
  lib/backend/k8s/conversion/conversion.go
  lib/backend/k8s/conversion/conversion_test.go
Labels: docs-not-required, release-note-required

#1374 Reduce log spam in host-local code
  lib/backend/syncersv1/updateprocessors/felixnodeprocessor.go
Labels: docs-not-required, release-note-required

#1375 Add CIDRs to the failsafes
  config/crd/crd.projectcalico.org_felixconfigurations.yaml
  lib/apis/v3/felixconfig.go
  lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  lib/backend/syncersv1/updateprocessors/felixconfigprocessor.go
  lib/upgrade/migrator/felixconfig.go
  lib/upgrade/migrator/felixconfig_test.go
Labels: docs-pr-required, release-note-not-required

#1378 Remove vendoring from libcalico, add openapi generation
  Makefile
  go.mod
  lib/apis/v1/openapi_generated.go
  lib/apis/v3/doc.go
  lib/apis/v3/openapi_generated.go
  lib/numorstring/doc.go
  lib/numorstring/openapi_generated.go
Labels: docs-not-required, merge-when-ready, release-note-not-required

#1384 More open API
  lib/apis/v1/doc.go
  lib/apis/v1/openapi_generated.go
  lib/apis/v3/openapi_generated.go
Labels: docs-not-required, release-note-not-required

#1382 Failsafe cidrs 3.18
  config/crd/crd.projectcalico.org_felixconfigurations.yaml
  lib/apis/v3/felixconfig.go
  lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  lib/backend/syncersv1/updateprocessors/felixconfigprocessor.go
  lib/upgrade/migrator/felixconfig.go
  lib/upgrade/migrator/felixconfig_test.go
Labels: docs-pr-required, release-note-not-required

#1381 Failsafe cidrs 3.17
  config/crd/crd.projectcalico.org_felixconfigurations.yaml
  lib/apis/v3/felixconfig.go
  lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  lib/backend/syncersv1/updateprocessors/felixconfigprocessor.go
  lib/upgrade/migrator/felixconfig.go
  lib/upgrade/migrator/felixconfig_test.go
Labels: docs-pr-required, release-note-not-required

#1380 Add CIDRs to the failsafes
  config/crd/crd.projectcalico.org_felixconfigurations.yaml
  config/crd/crd.projectcalico.org_ipamblocks.yaml
  lib/apis/v3/felixconfig.go
  lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  lib/backend/syncersv1/updateprocessors/felixconfigprocessor.go
  lib/upgrade/migrator/felixconfig.go
  lib/upgrade/migrator/felixconfig_test.go
Labels: docs-pr-required, release-note-not-required

#1379 Add CIDRs to the failsafes
  config/crd/crd.projectcalico.org_felixconfigurations.yaml
  config/crd/crd.projectcalico.org_ipamblocks.yaml
  lib/apis/v3/felixconfig.go
  lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  lib/backend/syncersv1/updateprocessors/felixconfigprocessor.go
  lib/upgrade/migrator/felixconfig.go
  lib/upgrade/migrator/felixconfig_test.go
Labels: docs-pr-required, release-note-not-required

#1385 Allow NP revision to be a single value
  lib/backend/k8s/conversion/conversion.go
  lib/backend/k8s/conversion/conversion_test.go
Labels: docs-not-required, merge-when-ready, release-note-not-required

#1388 Add manual field back that was removed
  config/crd/crd.projectcalico.org_ipamblocks.yaml
Labels: docs-not-required, release-note-not-required

#1389 Add manual field back that was removed
  config/crd/crd.projectcalico.org_ipamblocks.yaml
Labels: docs-not-required, release-note-not-required

#1363 Fix libcalico returning a generic kubernetes error
  lib/backend/k8s/resources/workloadendpoint.go
Labels: docs-not-required, merge-when-ready, release-note-required

#1387 Fill internal or external IP for HostIPKey if BGP is disabled
  lib/apis/v3/node.go
  lib/apis/v3/openapi_generated.go
  lib/backend/k8s/resources/node.go
  lib/backend/k8s/resources/node_test.go
  lib/backend/syncersv1/updateprocessors/felixnodeprocessor.go
  lib/validator/v3/validator.go
Labels: docs-pr-required, release-note-required

#1391 Pass revision information to List()
  lib/backend/k8s/k8s_test.go
  lib/backend/k8s/resources/customresource.go
Labels: docs-not-required, release-note-not-required

#1392 Add Status() method to Calico datastore error types
  lib/errors/errors.go
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1393 Add IPv6 network support for failsafe rules
  config/crd/crd.projectcalico.org_felixconfigurations.yaml
  lib/apis/v3/felixconfig.go
  lib/apis/v3/openapi_generated.go
  lib/backend/syncersv1/updateprocessors/felixconfigprocessor.go
  lib/numorstring/openapi_generated.go
  lib/upgrade/migrator/felixconfig.go
Labels: docs-not-required, release-note-not-required

#1394 Add back generated file
  lib/numorstring/openapi_generated.go
Labels: docs-not-required, release-note-not-required

#1396 Cleanup duplicate imports
  lib/upgrade/migrator/felixconfig.go
Labels: docs-not-required, release-note-not-required

#1395 Add IPv6 network support for failsafe rules
  config/crd/crd.projectcalico.org_felixconfigurations.yaml
  lib/apis/v3/felixconfig.go
  lib/backend/syncersv1/updateprocessors/felixconfigprocessor.go
  lib/upgrade/migrator/felixconfig.go
Labels: docs-not-required, release-note-not-required
