Repository projectcalico/libcalico-go, pull requests merged in 2021-12, with the labels that each got.

#1552 Replace github.com/dgrijalva/jwt-go with github.com/golang-jwt/jwt
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#1553 Automated cherry pick of #1552: Replace github.com/dgrijalva/jwt-go with
  go.mod
  go.sum
Labels: release-note-required, docs-not-required

#1554 Automated cherry pick of #1552: Replace github.com/dgrijalva/jwt-go with
  go.mod
  go.sum
Labels: release-note-required, docs-not-required

#1555 Add support for filtering debug logs on filename.
  lib/logutils/another_file_for_test.go
  lib/logutils/logutils.go
  lib/logutils/logutils_test.go
Labels: release-note-required, docs-pr-required, merge-when-ready

#1549 Add IPAM capability to release block affinity given a block object
  lib/ipam/interface.go
  lib/ipam/ipam.go
  lib/ipam/ipam_test.go
Labels: release-note-required, docs-not-required
